### ISSUE TITLE
Dokka does not add a link to the source code for the Android library.

### ISSUE THREAD

**Issue by kepocnhh** [Kotlin/dokka#2997] opened 2023-05-16 12:03 UTC
Dokka does not add a link to the source code for the Android library. Although it works for the Java library.

I made test projects to demonstrate accordingly: [Android](https://github.com/kepocnhh/DokkaAndroidLib), [Java](https://github.com/kepocnhh/DokkaJavaLib). There you can see the build script documentation. The build results can be viewed accordingly: [Android](https://kepocnhh.github.io/DokkaAndroidLib/doc/0.0.1), [Java](https://kepocnhh.github.io/DokkaJavaLib/doc/0.0.1/)

---

Assemble java lib documentation task:
```Kotlin
task<org.jetbrains.dokka.gradle.DokkaTask>("assembleDocumentation") {
    outputDirectory.set(buildDir.resolve("documentation"))
    moduleName.set(rootProject.name)
    moduleVersion.set(version.toString())
    dokkaSourceSets.getByName("main") {
        val path = "src/$name/kotlin"
        reportUndocumented.set(false)
        sourceLink {
            localDirectory.set(file(path))
            val url = "https://github.com/kepocnhh/DokkaJavaLib"
            remoteUrl.set(URL("$url/tree/${moduleVersion.get()}/lib/$path"))
        }
        jdkVersion.set(Version.jvmTarget.toInt())
    }
}
```

Screenshots:
<img width="810" alt="image" src="https://github.com/Kotlin/dokka/assets/6218886/f49c9589-e8ba-4dcc-a34c-b27813f8b245">

---

Assemble android lib documentation task:
```Kotlin

task<org.jetbrains.dokka.gradle.DokkaTask>("assemble${variant.name.capitalize()}Documentation") {
    outputDirectory.set(buildDir.resolve("documentation/${variant.name}"))
    moduleName.set(rootProject.name)
    moduleVersion.set(version.toString())
    dokkaSourceSets.create("${variant.name}Main") {
        val path = "src/main/kotlin"
        reportUndocumented.set(false)
        sourceLink {
            localDirectory.set(file(path))
            val url = "https://github.com/kepocnhh/DokkaAndroidLib"
            remoteUrl.set(URL("$url/tree/${moduleVersion.get()}/lib/$path"))
        }
        jdkVersion.set(Version.jvmTarget.toInt())
    }
}
```

Screenshots:
<img width="813" alt="image" src="https://github.com/Kotlin/dokka/assets/6218886/66ee9a4b-fcac-4534-b352-6e756c9b49b8">

---

- Operating system: macOS
- Build tool: Gradle 7.6.1
- Kotlin version: 1.7.10
- Dokka version: 1.8.10

**Comment by IgnatBeresnev** [comment] 2023-05-19 15:44
Thanks for the report! 

It looks to be an android-specific regression from 1.7.20, probably something to do with KGP/AGP, we'd have to take a closer look.

I'll close this issue as a duplicate of #2876 to keep the discussion/updates in a single place

**Closed by IgnatBeresnev** 2023-05-19 15:44 UTC
Labels: bug
