### ISSUE TITLE
Cannot document the receiver of an extension function using the `@reciever` block tag

### ISSUE THREAD

**Issue by AzimMuradov** [Kotlin/dokka#2025] opened 2021-07-13 22:17 UTC
**Describe the bug**
Cannot document the receiver of an extension function using the [`@reciever` block tag](https://kotlinlang.org/docs/kotlin-doc.html#receiver).

**Expected behaviour**
Expected to have a short description of the receiver.

**Screenshots**
![image](https://user-images.githubusercontent.com/31899809/125531534-c5d06b13-4f08-4f36-8e75-8af5dee64afe.png)
![image](https://user-images.githubusercontent.com/31899809/125531549-1af242d4-be9f-428c-889e-002b07c93040.png)

**To Reproduce**
```kotlin
package test

/**
 * Foo foo foo.
 */
sealed class Foo {

    /**
     * Bar bar bar.
     *
     * @receiver Int int int.
     */
    fun Int.bar(): String = "$this"
}

/**
 * Baz baz baz.
 *
 * @receiver Char char char.
 */
fun Char.baz(): String = "$this"
```

[test-dokka.zip](https://github.com/Kotlin/dokka/files/6812266/test-dokka.zip)

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
tasks.dokkaHtml {
    outputDirectory.set(buildDir.resolve("dokka"))

    // Set module name displayed in the final output
    moduleName.set("library")

    doLast {
        println("View docs at:")
        println("file://$buildDir/dokka/index.html")
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle 7.1
- Dokka version: 1.5.0

**Comment by msink** [comment] 2021-07-14 07:25
duplicate of #1109

**Closed** 2021-07-14 12:18 UTC
Labels: bug
