### ISSUE TITLE
suppressedFiles / perPackageOption: suppress do not work with Java sources

### ISSUE THREAD

**Issue by bsiegel** [Kotlin/dokka#1491] opened 2020-09-18 20:22 UTC
Neither suppression option results in the specified package hierarchy or file path hierarchy being excluded from documentation when the project being documented is written in Java. Both options appear to have no effect.

**Expected behaviour**
Suppressed packages (and their subpackages), and suppressed file paths, are excluded from documentation.

**To Reproduce**
Apply the below configuration stanzas to a project written in Java. Configure Dokka with the kotlin-as-java-plugin.

**Dokka configuration**

```groovy
// Tried this
perPackageOption {
    prefix = "com.example.exampleapp.internal"
    suppress = true
}

// Also tried
suppressedFiles = ["src/main/java/com/example/exampleapp/internal"]
```

I also tried the newer syntax:
```groovy
// Tried this
perPackageOption {
    prefix.set("com.example.exampleapp.internal")
    suppress.set(true)
}

// Also tried
suppressedFiles.setFrom(files("src/main/java/com/example/exampleapp/internal"))
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.6
- Dokka version: 1.4.0

**Additional context**
- I have not tested this with a Kotlin project yet, but I assume that this is Java specific or someone would have reported a general issue with these options not working by now.
- I have tried dev builds in the 1.4.10 series and they exhibit the same problem (latest tested: dev-72).

**Comment by BarkingBad** [comment] 2020-10-02 07:40
Could not reproduce, everything works fine for me. Can you provide sample project where the problem occurs?

**Comment by BarkingBad** [comment] 2020-10-02 08:37
Hey, @bsiegel 

I created repository that I think is ready-to-go example how to setup things properly for suppressing packages
https://github.com/BarkingBad/dokka-proof--1491

You can see that in directory `dokka` there is only `make.me.visible` package, while `make.me.suppressed` is in fact cut out.

Tested for `1.4.10-dev-72`

Please let me know if the issue no longer persist, so I can close the issue

**Comment by bsiegel** [comment] 2020-10-02 19:25
@BarkingBad Thanks for this, I did a little more research and I figured out that if I have the `perPackageOption` block AFTER one (or more) `externalDocumentationLink` blocks it does not work, but if I move it before them, then it works as expected.

Try adding the following before your `perPackageOption` block in your sample (I'm using Groovy syntax, so translate to Kotlin as needed):

```groovy
externalDocumentationLink {
    url.set(URL("https://square.github.io/okhttp/3.x/okhttp/"))
    packageListUrl.set(URL("https://square.github.io/okhttp/3.x/okhttp/package-list"))
}
```

**Comment by bojankoma** [comment] 2020-11-09 21:04
Actually, I can reproduce this in a pure Kotlin project.
Configuration file is [here](https://github.com/infinum/android_dbinspector/blob/develop/dokka.gradle).
No `externalDocumentationLink` at all in my case, but I have several `perPackageOption` which are not suppressed.

**Comment by robertszuba** [comment] 2021-02-15 11:12
Having the same issue. Our Android library uses both Java and Kotlin classes. Even the simplest configuration option:
```
dokkaJavadoc.configure {
  dokkaSourceSets {
    named("main") {

      perPackageOption {
        prefix.set("com.onegini.mobile.sdk.android.internal")
        // also tried
        // prefix = "com.onegini.mobile.sdk.android.internal"
        // matchingRegex.set(".*\.internal.*")
        suppress.set(true)
      }
    }
  }
}
```
doesn't work - the internal package is not suppressed. 

Tested on 
- MacOS Catalina 10.15.6
- Dokka 1.4.20
- Kotlin 1.4.21-2
- com.android.tools.build:gradle:3.6.3

**Comment by robertszuba** [comment] 2021-03-09 12:38
What is the status of this issue? Was it confirmed and is someone working on a fix? Do you need more info to properly investigate it?

Our team really wanted to start using Dokka but this issue is a blocker for us.

**Comment by kamildoleglo** [comment] 2021-03-09 15:25
@bojankoma your Dokka configuration is incorrect. Firstly, we dropped `prefix` in favour of `matchingRegex`. Secondly, `Platform.jvm` fully-qualified name has changed. And thridly, nothing (apart form one object) is getting documented in your project since everything is `internal` and it's filtered by default. You should set `includeNonPublic.set(true)` if you want to see those things documented. Just checked, filtering works as expected. I'd also advise migrating to `.kts` files as debugging Groovy files is getting harder day by day (recently we get generic `NamedDomainObjectContainer#create(String) on ... container cannot be executed in the current context` exceptions for any problem in a `.gradle` file)

**Comment by kamildoleglo** [comment] 2021-03-09 15:28
@robertszuba - you also have `prefix` instead of `matchingRegex`. Also please confirm that you configure the right source set (you can also use `configureEach {}` )

**Comment by kamildoleglo** [comment] 2021-03-09 15:29
I'm 99% sure suppressing files works correctly, we do have quite extensive tests for them and it doesn't matter where the sources come from

**Comment by robertszuba** [comment] 2021-03-11 13:44
@kamildoleglo Thanks for the answer. I took another look on my setup and was finally able to make it work. Most options that I tried earlier were invalid:
`prefix.set("com.onegini.mobile.sdk.android.internal")` was using `prefix` as you pointed out;
`prefix = "com.onegini.mobile.sdk.android.internal"` was using both `prefix` and old syntax;
`matchingRegex.set(".*\.internal.*")` was using incorrect escaping (should be `".*\\.internal.*"`)

The most difficult error to spot was when I actually had a proper regex, but some other setting was using the old assigment syntax:
```groovy
    named("main") {
      jdkVersion = 8 // <- old syntax
      // ... more options skipped

      perPackageOption {
        matchingRegex.set(".*\\.internal.*") // proper setting
        suppress.set(true)
      }
    }
```
because in such case the "suppress" was also not working correctly and I was focused on the regex syntax, while the actual issue was in the other place.

All in all I can blame myself for those issues, but I would also suggest that Dokka could have some kind of errors/warning logs to prevent the old syntax usage, or mixing the old and new syntax if it causes such issues.

**Comment by kamildoleglo** [comment] 2021-03-11 14:18
Thanks for the feedback @robertszuba ! Yeah, I agree that we should have some warnings about that, but I think that those information is not available to us. This is a Gradle configuration and their DSL does not provide any info on which notation was used

**Comment by therock24** [comment] 2021-04-13 15:08
Hey guys, sorry for bringing this topic up again, but I have been a couple of days trying to suppress packages and files. Only after reading this I was able to suppress a package.
But.. What about files/classes?
What if I have only 1 class in the package that I want to suppress documentation and the others not?
Has anyone done this successfully?
I've tried using `matchingRegex.set("com.example.test.MyClass")` and it just won't work. Apparently it only supresses if the regex matches a package. 
I've searched for a while and couldn't find any answer for this, I am surprised how no one is talking about it being such a common scenario.

**Comment by kamildoleglo** [comment] 2021-04-13 15:40
TBH it isn't a common scenario. Most of the time your public API is what you want to document, apart from the tests, which should have their separate package(s) and then you can just suppress this package. 
Anyway, suppressing files is not possible (you can probably not document them by manually setting the sourceRoots to the other files), you can however suppress a certain class with the `@suppress` annotation I believe

**Comment by therock24** [comment] 2021-04-14 14:56
> TBH it isn't a common scenario. Most of the time your public API is what you want to document, apart from the tests, which should have their separate package(s) and then you can just suppress this package.
> Anyway, suppressing files is not possible (you can probably not document them by manually setting the sourceRoots to the other files, but this is kind of not worth it), you can however suppress a certain class with the `@suppress` annotation I believe: https://kotlinlang.org/docs/kotlin-doc.html
> Javadoc comments don't support any suppressing whatsoever, so there is an Android plugin for Dokka which adds support for the `@hide` annotation: http://kotlin.github.io/dokka/1.4.32/user_guide/android-plugin/android-plugin/

Thank you so much for the reply! I understand it might not be common scenario, it's probably more of an architecture decision, but anyway, the `@suppress` tag did the magic for me (since my library is purely written in Kotlin), and i'm really happy it worked out.

To sum up and help other in this situation, using the dokka version 1.4.30+, you can do it like this:

**To supress a whole package (works for both Java and Kotlin classes)**: 
Here i show `dokkaHtml` but you can use any of the other formats, such as `dokkaJavadoc`.
```
dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            ...
            perPackageOption {
                matchingRegex.set("com.example.package") // or any other valid regex you wish (only for packages)
                suppress.set(true)
            }
            ...
      }
   }
}
```

**To suppress a file/class: (only for Kotlin docs)**
Add this to you class documentation.
```
/**
 * @suppress
 */
class Myclass() {
```

For **javadoc**, like @kamildoleglo said, you would need the plugin http://kotlin.github.io/dokka/1.4.32/user_guide/android-plugin/android-plugin/ and use the `@hide` annotation instead of `@suppress`.

**Comment by IgnatBeresnev** [comment] 2022-04-27 14:09
Seems like of the problems that were discussed here have been resolved. Closing the issue for now, let us know if you keep seeing this.

**Closed by IgnatBeresnev** 2022-04-27 14:09 UTC
Labels: bug
