### ISSUE TITLE
Enum names overlap

### ISSUE THREAD

**Issue by RealYusufIsmail** [Kotlin/dokka#2715] opened 2022-10-15 21:29 UTC
**Describe the bug**
With long enum names they are overlapping 
**Expected behaviour**
No to overlap 
**Screenshots**

<img width="1297" alt="Screenshot 2022-10-15 at 22 29 04" src="https://user-images.githubusercontent.com/67903886/196008254-c5d4d2a2-5ddc-4044-89fa-1571e04173c6.png">

**Installation**
- Operating system: Linux
- Build tool: Gradle v7.5.1
- Dokka version: 1.7.10

**Additional context**
Add any other context about the problem here

**Are you willing to provide a PR?**
No

**Comment by IgnatBeresnev** [comment] 2022-11-17 03:23
Thanks for noticing and submitting the bug!

To reduce information spreading, I'll close this issue as a duplicate of #2516, please follow it for updates.

**Closed by IgnatBeresnev** 2022-11-17 03:23 UTC
Labels: bug
