### ISSUE TITLE
Crash on Markdown table

### ISSUE THREAD

**Issue by swankjesse** [Kotlin/dokka#1683] opened 2020-12-30 20:11 UTC
**Describe the bug**
Okio includes this table in the documentation of [Path.kt](https://github.com/square/okio/blob/ff192b74acdc5f1d83c3fb7ed108f3f05ab03f87/okio/src/commonMain/kotlin/okio/Path.kt). This is a simpler table that also triggers the crash.

```
| Path                         | Notes                          |
| :--------------------------- | :----------------------------- |
| /                            | root                           |
```

When running `./gradlew :okio:dokkaGfm` Dokka crashes. Removing the table prevents the crash.

```
$ ./gradlew :okio:dokkaGfm
...
> Task :okio:dokkaGfm
Dokka 1.4.* is an alpha project
Initializing plugins
Validity check
Creating documentation models
Transforming documentation model before merging
Merging documentation models
Transforming documentation model after merging
Creating pages
Transforming pages
Rendering
Failed to write org.jetbrains.dokka.base.renderers.FileWriter@68b4ae71. Parent job is Cancelling
Failed to write org.jetbrains.dokka.base.renderers.FileWriter@68b4ae71. Parent job is Cancelling
Failed to write org.jetbrains.dokka.base.renderers.FileWriter@68b4ae71. Parent job is Cancelling

kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=ScopeCoroutine{Cancelling}@4d2d5cb9
Caused by: java.lang.IllegalArgumentException: Count 'n' must be non-negative, but was -3.
        at kotlin.text.StringsKt__StringsJVMKt.repeat(StringsJVM.kt:695)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildTable(GfmPlugin.kt:217)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildTable(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:117)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildPlatformDependentItem(GfmPlugin.kt:146)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildPlatformDependent(GfmPlugin.kt:134)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildPlatformDependent(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:120)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$buildGroup$1.invoke(DefaultRenderer.kt:19)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:72)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.wrapGroup(GfmPlugin.kt:51)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildGroup(DefaultRenderer.kt:63)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildContentNode(DefaultRenderer.kt:118)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build(DefaultRenderer.kt:100)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.build$default(DefaultRenderer.kt:98)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.buildPageContent(DefaultRenderer.kt:158)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer$renderPage$2.invoke(GfmPlugin.kt:340)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer$renderPage$2.invoke(GfmPlugin.kt:51)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.buildPage(GfmPlugin.kt:245)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.renderPage$suspendImpl(GfmPlugin.kt:340)
        at org.jetbrains.dokka.gfm.CommonmarkRenderer.renderPage(GfmPlugin.kt)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$renderPages$2.invokeSuspend(DefaultRenderer.kt:188)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$renderPages$2.invoke(DefaultRenderer.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer.renderPages(DefaultRenderer.kt:187)
        at org.jetbrains.dokka.base.renderers.DefaultRenderer$renderPages$2$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(DefaultRenderer.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Expected behaviour**
No crash.

**To Reproduce**

```
git clone git@github.com:square/okio.git
git checkout eb53e5daa97745cec268f0a03a842943405ed555
./gradlew :okio:dokkaGfm
```

**Dokka configuration**

```groovy
def dokkaConfiguration = {
  outputDirectory.set(file("$rootDir/docs/2.x"))

  dokkaSourceSets {
    configureEach {
      reportUndocumented.set(false)
      skipDeprecated.set(true)
      jdkVersion.set(8)
      perPackageOption {
        matchingRegex.set("com\\.squareup.okio.*")
        suppress.set(true)
      }
      perPackageOption {
        matchingRegex.set("okio\\.internal.*")
        suppress.set(true)
      }
    }
  }
}

dokkaGfm.configure(dokkaConfiguration)
dokkaHtml.configure(dokkaConfiguration)
```

**Installation**
- Operating system: macOS 10.15.7
- Build tool: Gradle 6.7.1
- Dokka version: 1.4.20

**Comment by kamildoleglo** [comment] 2020-12-30 20:34
Duplicate of https://github.com/Kotlin/dokka/issues/1592

**Closed by kamildoleglo** 2020-12-30 20:34 UTC
Labels: bug
