### ISSUE TITLE
Table from markdown is not rendering ❌

### ISSUE THREAD

**Issue by jimfilippou** [Kotlin/dokka#825] opened 2020-04-26 12:46 UTC
**Is your feature request related to a problem? Please describe**
If the project claims to support markdown, it should support it as a whole and not just a few elements. 

**Describe the solution you'd like**
I would love to provide markdown tables and be able to render them on the documentation

**Describe alternatives you've considered**
An alternative is to show the data in a different way, which is **not** a solution

**Comment by kamildoleglo** [comment] 2020-07-07 23:38
Markdown tables are in fact not a part of the official markdown syntax, they are an extension to it (please see https://www.markdownguide.org/basic-syntax)

That being said, they will probably be supported in 0.11.0. 

Closing as a duplicate of https://github.com/Kotlin/dokka/issues/199

**Closed by kamildoleglo** 2020-07-07 23:38 UTC
Labels: enhancement
