### ISSUE TITLE
How to properly display gradle flavor classes? 

### ISSUE THREAD

**Issue by serdelPL** [Kotlin/dokka#1937] opened 2021-05-26 12:39 UTC
**Question**
I am struggling to properly display classes that have different implementation per different flavors. Because of the unresolved issue:
https://github.com/Kotlin/dokka/issues/1538

The default implementation is not acceptable. 

The further I went is creating different source sets an suppres the main one, but for some reason I still see `androidJvm` with my flavor related packages. 

`dokkaHtml {

    suppressObviousFunctions.set(true)

    dokkaSourceSets {

        named("main") {
            suppress.set(true)
        }

        register("Flavor1") {
            sourceRoots.from(file("src/main"))
            sourceRoots.from(file("src/flavor1")) //classes only present in flavor1 and flavor2 not in main
        }
        register("Flavor2") {
            sourceRoots.from(file("src/main"))
            sourceRoots.from(file("src/flavor2"))//classes only present in flavor1 and flavor2 not in main
        }
        }
    }
}`

Ideally I would prefer to have 2 separate html files for my flavor1 and flavor2, but I failed to figure out how to do it.

**Comment by MarcinAman** [comment] 2021-05-27 08:59
Linked issue is posted for dokka 0.10, which is not supported. Which version are you using?

**Comment by serdelPL** [comment] 2021-05-27 09:49
Hello,

I'm using version 1.4.32 and face the same problem described in the issue.

**Comment by MarcinAman** [comment] 2021-05-27 12:20
Android flavours should be displayed as different sourcesets. Could you post a link to your project / reproducable case?

**Comment by kamildoleglo** [comment] 2021-05-31 11:05
You can change the `androidJvm` (which is a default) to the flavour name: 

```
tasks {
    dokkaHtml {
        suppressObviousFunctions.set(true)
        dokkaSourceSets {
            configureEach {
                if (it.name in ["prod", "dev"]) {
                    suppress.set(false)
                    displayName.set(it.name)
                } else {
                    suppress.set(true)
                }
            }
        }
    }
}
```

**Comment by serdelPL** [comment] 2021-06-09 08:54
Thank you for the reply @kamildoleglo  and sorry for a late response. I tried the approach you suggested but I still have some issue. I am not sure how to use the classpath property to include source code from main part so I used the sourceRoots property. This however still causes multiple problems:

`
dokkaHtml {
    suppressObviousFunctions.set(true)
    dokkaSourceSets {
        configureEach {
            if (it.name in ["prod", "dev"]) {
                suppress.set(false)
                displayName.set(it.name)
//                classpath.from(file("src/main"))
                sourceRoots.from(file("src/main"))
            } else {
                suppress.set(true)
            }
        }
    }
}`

I have also change the declarations of the prod implementation code to make it work with different object types (it's nothing uncommon to have in kotlin library projects):

dev flavor:
`fun connect(demoRequest: DemoRequest): DemoResult`
prod flavor:
`fun connect(prodRequest: ProdRequest): ProdResult`

However it seems that the prod implementation is nowhere to be found in the output html. the changes are present on the sample repository if you want to check. 

Firstly, please note the amount of duplicates produced in the output:
![dokka_flavor1](https://user-images.githubusercontent.com/20315656/121324100-b3e94100-c910-11eb-9581-e46e369bb9e8.png)
Also The displayName is nowhere to be found:
![dokka_flavor2](https://user-images.githubusercontent.com/20315656/121324187-c6fc1100-c910-11eb-966e-77538c053573.png)
Thirdly, please note that both display of CommunicationManager work on the DemoReqest/DemoResult objects and the Prod implementation is nowhere to be found:

![dokka_flavor3](https://user-images.githubusercontent.com/20315656/121324305-e5620c80-c910-11eb-89e2-81c33f5ed1c3.png)
![dokka_flavor4](https://user-images.githubusercontent.com/20315656/121324322-e7c46680-c910-11eb-9305-1b75be20cc22.png)

**Comment by kamildoleglo** [comment] 2021-06-09 10:52
The duplicates may be caused by the `sourceRoots` that you used and if not, by not setting a proper flavour display name. You have to change the default `androidJvm` name to whatever you want, that's why I posted a code with `                 displayName.set(it.name)` for each sourceSet

**Comment by kamildoleglo** [comment] 2021-06-09 10:55
Are you sure you configured the right task? With the configuration I posted before, I get proper docs: 
![image](https://user-images.githubusercontent.com/9080183/121342437-e9e2f100-c921-11eb-9805-c81bf4dd2e8a.png)

**Comment by kamildoleglo** [comment] 2021-06-09 10:58
With added `sourceRoot` for the `src/main` the model looks fine too: 
![image](https://user-images.githubusercontent.com/9080183/121342850-5b22a400-c922-11eb-8580-e9bffab545be.png)

**Comment by kamildoleglo** [comment] 2021-06-09 11:09
For this project structure though instead of adding sourceRoots to each dokka source set, I'd personally unsuppress the `main` source set too, to have the common model with a common label (you can rename it to "common" if you want to) and added the main classpath to the flavours. You can even set a `dependsOn` to have it merged correctly (the classpath will then be fine too):

```
tasks {
    dokkaHtml {
        suppressObviousFunctions.set(true)
        dokkaSourceSets {
            configureEach {
                if (it.name in ["prod", "dev", "main"]) {
                    suppress.set(false)
                    displayName.set(it.name)
                    if (it.name != "main") {
                        dependsOn("main")
                    }
                } else {
                    suppress.set(true)
                }
            }
        }
    }
}
``` 
It can probably be written cleaner

**Comment by serdelPL** [comment] 2021-06-11 13:24
ok this is weird and I think I found the problem. I am configuring the dokka in a seperate gradle file which I apply in my :app build.gradle. When I moved the dokka configuration to the bottom of build.gradle and wrap it with `tasks{}` block it works. @kamildoleglo  Is this normal or is it a bug? why is it like that?

**Comment by kamildoleglo** [comment] 2021-06-11 13:30
You're probably lacking type-safe accessors although I don't know why you don't get an error:
https://docs.gradle.org/6.8.1/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api

**Comment by IgnatBeresnev** [comment] 2022-04-26 19:59
This seems to have been resolved :) I'll close this for now, but do let us know if you keep experiencing this issue

**Closed by IgnatBeresnev** 2022-04-26 19:59 UTC
Labels: question
