### ISSUE TITLE
Publish dokka-maven-plugin to Maven Central

### ISSUE THREAD

**Issue by bdemers** [Kotlin/dokka#791] opened 2020-04-02 23:16 UTC
The Dokka Maven Plugin, should be available on Maven Central (just like the other Kotlin libs and plugins)

**Comment by benjamin-bader** [comment] 2020-05-15 04:00
Yes, please - I try to avoid jcenter wherever possible and would very much appreciate dokka being available on Central.

**Comment by kamildoleglo** [comment] 2020-07-07 23:23
Closing as a duplicate of https://github.com/Kotlin/dokka/issues/41

**Closed by kamildoleglo** 2020-07-07 23:23 UTC
Labels: enhancement
