### ISSUE TITLE
Property names overflow into description

### ISSUE THREAD

**Issue by nk-coding** [Kotlin/dokka#2657] opened 2022-09-06 17:03 UTC
**Describe the bug**
At the properties table, the name of the property is not wrapped if snake-case is used and overflows into the description.

**Expected behaviour**
Make the property name not overflow into the description. I personally would prefer breaking after the underscore (by inserting a `<wbr>` like it is already done for camel case). Additionally, maybe also add a `word-break: break-word` so that very long words which can't be wrapped by the rules above still don't overflow (imho these breaks are still better than overflow, however I can understand if you have a different opinion there)

**Screenshots**
![image](https://user-images.githubusercontent.com/53957498/188696332-c38ec243-9eee-4882-ab10-52706cf8d904.png)

**To Reproduce**
Create documentation for a long name in snake-case, e.g. "THIS_IS_A_VERY_VERY_LONG_TEST_PROPERTY"

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.5.1
- Dokka version: 1.7.10

**Are you willing to provide a PR?**
I currently don't know where to fix this, however if you provide me some guidance I would try my best

**Comment by IgnatBeresnev** [comment] 2022-09-07 20:51
Hi! I'll close this issue as a duplicate of https://github.com/Kotlin/dokka/issues/2516, but thanks for reporting it!

We might drop the left column altogether, which would resolve the problem, or indeed add word breaks.

**Closed by IgnatBeresnev** 2022-09-07 20:51 UTC
Labels: bug
