### ISSUE TITLE
Change hosting repository

### ISSUE THREAD

**Issue by MiSikora** [Kotlin/dokka#1730] opened 2021-02-04 18:12 UTC
**Is your feature request related to a problem? Please describe**

JFrog [announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter) yesterday that they will sunset JCenter May 1st.

**Describe the solution you'd like**

A migration to a different repository would be welcome.

**Describe alternatives you've considered**

I don't think there are reasonable alternatives.

**Additional context**

N/A

**Comment by kamildoleglo** [comment] 2021-02-04 18:36
Duplicate of https://github.com/Kotlin/dokka/issues/1725

**Closed by kamildoleglo** 2021-02-04 18:36 UTC
Labels: enhancement
