### ISSUE TITLE
Unable to use dokka Gradle plugin without JCenter

### ISSUE THREAD

**Issue by szpak** [Kotlin/dokka#1741] opened 2021-02-10 23:16 UTC
**Describe the bug**

It is unable to [build](https://github.com/gradle-nexus/publish-plugin/runs/1875382589?check_suite_focus=true#step:4:56
) a project using Dokka Gradle plugin without JCenter (`jcenter()`):

```
> Task :dokkaJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dokkaJavadoc'.
> Could not resolve all files for configuration ':dokkaJavadocPlugin'.
   > Could not find org.jetbrains.dokka:javadoc-plugin:1.4.20.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/dokka/javadoc-plugin/1.4.20/javadoc-plugin-1.4.20.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dokkaJavadoc'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
```

Due to its "soon" shut down (~~1st May 2021~~ "clarified" to 1st Feb 2022 :-D ) it would be good to cover it. In Maven Central there is only 1.4.10.2 [available](https://repo.maven.apache.org/maven2/org/jetbrains/dokka/javadoc-plugin/).

**Expected behaviour**
Everything works fine without `jcenter()`.

**To Reproduce**
`./gradlew :dokkaJavadoc` for gradle-nexus-publish-plugin from that [commit](https://github.com/gradle-nexus/publish-plugin/commit/42a7a7c8d062b7f930969e24d0876af115182d1a) - preferably on a system without cached artifacts

**Dokka configuration**
`id("org.jetbrains.dokka") version "1.4.20"`

**Comment by kamildoleglo** [comment] 2021-02-10 23:24
Duplicate of https://github.com/Kotlin/dokka/issues/1725

**Closed by kamildoleglo** 2021-02-10 23:24 UTC
Labels: bug
