### ISSUE TITLE
KDoc emphasis is ignored

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1902] opened 2021-05-04 08:43 UTC
If we add emphasis markup on kdoc:
```
/**
 * Hi there! This is an _emphasis_ test!
 */
```
It is ignored on both HTML and GFM backend. The text appears as normal, without emphasizing the word.

Also, as noted here:
https://kotlinlang.org/docs/kotlin-doc.html#inline-markup
"For inline markup, KDoc uses the regular Markdown syntax, extended to support a shorthand syntax for linking to other elements in the code."

So I would expect the word to be emphasized somehow, perhaps in bold, itallic or underlined.

**Comment by MarcinAman** [comment] 2021-05-04 17:25
Hi, this is a duplicate of https://github.com/Kotlin/dokka/issues/1468 which is already planned

**Closed by MarcinAman** 2021-05-04 17:25 UTC
Labels: bug
