### ISSUE TITLE
Invalid link for item from clashed declarations in different platforms

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2413] opened 2022-03-30 14:25 UTC
Create a multi-module project with few modules. In one of them, apply a Kotlin multiplatform plugin and create a function with the same name. Generate the documentation. Link for the object in grid will lead to invalid module (see the screenshot: link from clash function in module `bmodule` leads to `amodule`).

With the flag `mergeImplicitExpectActualDeclarations` the same scenario works correctly.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/7689049/160856690-22e72c20-24fe-4e07-a697-0e8121eed993.png">

**To Reproduce**
[repro.zip](https://github.com/Kotlin/dokka/files/8381316/repro.zip)

**Installation**
- Dokka version: 1.6.20

**Comment by vmishenev** [comment] 2022-03-31 11:58
[The same issue ](https://github.com/Kotlin/dokka/issues/2272)

**Comment by IgnatBeresnev** [comment] 2022-04-26 17:57
Closing this as duplicate of #2272 to reduce spreading information

**Closed by IgnatBeresnev** 2022-04-26 17:57 UTC
Labels: bug
