### ISSUE TITLE
Don't ever print <ERROR CLASS> to the output

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/dokka#63] opened 2016-03-14 12:17 UTC
It's much better to just pass unknown types through to the output as plain text rather than give the (entirely useless) <ERROR CLASS> type token to the reader.

**Comment by Hazealign** [comment] 2016-06-24 08:58
👍  Agree.

**Comment by semoro** [comment] 2016-11-03 18:41
Related to #79

**Comment by semoro** [comment] 2016-11-08 18:03
Is this actual in flavor of #79 fix?

**Comment by semoro** [comment] 2017-05-02 15:25
Seems not a problem now, closing

**Closed by semoro** 2017-05-02 15:25 UTC

**Comment by pvillela** [comment] 2019-01-27 19:07
The problem still exists with the Dokka fatjar.

**Comment by semoro** [comment] 2019-01-30 13:53
In some positions, Dokka complete unable to determine the type, if something went wrong. 
It is unclear what behaviour should be in such cases
`fun foo() = Bar() + Bar() // Bar is unresolved/undefined`

@pvillela If such problem reproduces for you, it is possible result of missing dependencies, please clarify your case

**Comment by pvillela** [comment] 2019-01-30 16:43
Thanks Simon. The functions in question had explicit signatures.  The Dokka
Gradle plugin gave me the correct results while the Dokka fatjar gave me
several <ERROR CLASS> results, even though I used the same classpath and
sources in both cases.

**Comment by semoro** [comment] 2019-01-31 10:47
@pvillela Check also that at time fatjar invoked all classpath jars exists. Basically Gradle plugin uses same fatjar so it seems strange for me

**Comment by pvillela** [comment] 2019-02-09 09:10
Thanks, Simon.  I have done what you recommended but the problem is still
there.  I'm attaching 4 files:

   1. Snippet from top-level gradle.kotlin.kts that shows that the Dokka
   task and the Dokka fatjar are using exactly the same sources and classpath.
   2. The script i'm using to run the fatjar
   3. index-outline.html from running the Dokka task
   4. index-outline.html from running the fatjar.  This file is visibly
   smaller than the one produced by the Dokka task.

Regards,
Paulo

**Comment by asm0dey** [comment] 2022-07-29 16:43
It's either regression or the new issue, but as I said here: https://github.com/Kotlin/dokka/issues/503#issuecomment-1199713556 we're hitting this hard
