### ISSUE TITLE
Property documentation is not handled correctly when is defined in parent

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1899] opened 2021-04-29 14:47 UTC
Reproducable case:
```
/**
 * Class description blah, blah, blah.
 *
 * @property property Something. Another something. And blah, blah, blah.
 * 
 * @constructor Creates a new instance, blah, blah.
 */
data class MyClass(val property: String)
```

**Comment by IgnatBeresnev** [comment] 2023-03-13 22:32
It's unclear what is meant by "not handled correctly". 

As of Dokka 1.8.10, documentation for the property is propagated as expected, unless I'm missing something. Here's the  output:

![2023-03-13_23-27-01](https://user-images.githubusercontent.com/22685910/224846564-3af1fa63-72e9-46d3-8bd3-6e793f51a2c0.png)

___

I'll close the issue as unable to reproduce / fixed, but do let me know if I misunderstood what the reported problem was.

**Closed by IgnatBeresnev** 2023-03-13 22:32 UTC
Labels: bug
