### ISSUE TITLE
Javadoc does not generate documentation for Java static inner classes.

### ISSUE THREAD

**Issue by bsiegel** [Kotlin/dokka#1240] opened 2020-07-30 23:50 UTC
**Describe the bug**
When generating Javadoc, static inner classes are listed within their containing class's documentation, but no docs are generated for the static inner class itself.

When generating HTML, docs are correctly generated for static inner classes.

**Expected behaviour**
Javadoc documentation should be generated for static inner classes.

**To Reproduce**
Create a static inner class with some constructors / methods / etc. Add some documentation. Then simply run the `dokkaJavadoc` and `dokkaHtml` tasks.

```java
/**
 * A containing class.
 */
public class MyClass {
    /**
     * A static inner class.
     */
    public static class Inner {
        private String value;

        /**
         * Creates an Inner with the provided value.
         *
         * @param value The value to provide.
         */
        public Inner(String value) {
          this.value = value;
        }

        /**
         * Gets the provided value.
         *
         * @return The provided value.
         */
        public String getValue() {
            return value;
        }
    }
}
```

**Screenshots**
![Screen Shot 2020-07-30 at 4 52 37 PM](https://user-images.githubusercontent.com/96068/88985495-464a9e00-d285-11ea-8f3a-aa770cd4a61a.png)

**Dokka configuration**
Configuration of dokka used to reproduce the bug

**Installation**
- Operating system: macOS 10.15
- Build tool: Gradle v6.5.1
- Dokka version: 1.4-mc-1

**Comment by kamildoleglo** [comment] 2020-07-30 23:57
Partially a duplicate of https://github.com/Kotlin/dokka/issues/983, leaving open for now though

**Comment by vmishenev** [comment] 2021-09-14 19:10
It's fixed by https://github.com/Kotlin/dokka/pull/1295

**Closed by vmishenev** 2021-09-14 19:10 UTC
Labels: bug, Javadoc
