### ISSUE TITLE
Add flag to hide all inherited members

### ISSUE THREAD

**Issue by BarkingBad** [Kotlin/dokka#1501] opened 2020-09-22 12:24 UTC
There should be possibility to hide all inherited (aka `FAKE_OVERRIDEN`) members of class

**Comment by prateem** [comment] 2020-10-20 08:28
Came here from [this SO post](https://stackoverflow.com/questions/63398436/ignore-base-class-view-public-functions-in-subclass-documentation-with-dokka).

Would love to see this make it through sometime soon. Thanks for the awesome tool!

**Comment by shipsywor** [comment] 2021-03-16 12:03
Has this important issue addressed yet? Been 6 months! It makes dokka completely unusable for Android projects with hundred of functions inherited. The functions I defined in the class are impossible to find and very cluttered.

Details: https://github.com/Kotlin/dokka/issues/1780

**Comment by zsmb13** [comment] 2021-03-16 12:12
In our project, we ended up using the `separateInheritedMembers` option with some convoluted Gradle config, [as seen here](https://github.com/GetStream/stream-chat-android/blob/81ac5f3c606237054b3ad473a35863875103ea98/scripts/publish-mavencentral.gradle#L16-L20). 

This puts all the inherited junk into a separate tab at least, [see an example here](https://getstream.github.io/stream-chat-android/stream-chat-android-ui-components/stream-chat-android-ui-components/io.getstream.chat.android.ui.message.list/-message-list-view/index.html)

![image](https://user-images.githubusercontent.com/12054216/111307023-35566d80-8659-11eb-92e3-cd18f06799b4.png)

**Comment by shipsywor** [comment] 2021-03-16 12:40
@zsmb13 Thank you! got it working.

Had to change configuration a little from your getstream example.

I had to use for dokka v1.4.30

```

tasks.withType(dokkaHtml.getClass()).configureEach {
    pluginsMapConfiguration.set(
            ["org.jetbrains.dokka.base.DokkaBase": """{ "separateInheritedMembers": true}"""]
    )
}
```

But still hoping for more flexible solution by the dokka maintainers as it only works with HTML as you mentioned.

**Comment by zsmb13** [comment] 2021-03-16 12:57
Oh yes, the task to modify depends on whether you use multi module dokka or not, either dokkaHtml or dokkaHtmlPartial.

**Comment by kamildoleglo** [comment] 2021-03-16 13:25
This should be fixed in `1.4.30` I believe, could you check that in your projects please?

**Comment by hpehl** [comment] 2021-03-16 15:32
I can confirm that it is fixed now.

**Comment by shipsywor** [comment] 2021-03-16 15:40
How does the v1.4.30 fixes it? How should we use the `hide` flag with respect to Android Gradle project? A small sample configuration here or on docs would be great to try it out.

@hpehl Can you please show how you tried that with example?

**Comment by kamildoleglo** [comment] 2021-03-16 16:07
Fake overrides should be filtered out by default in `1.4.30`

**Comment by hpehl** [comment] 2021-03-16 16:20
@shipsywor sorry I mixed up issues. When I claimed that is was fixed I was referring to #1779 not this issue.

**Comment by shipsywor** [comment] 2021-03-16 17:23
@kamildoleglo On Version 1.4.30, the result is still not as desired.

I have created a sample project here: https://github.com/shipsywor/dokka-android-kotlin-sample

As you stated, fake overrides should be filtered by default BUT they are not.

![output1](https://user-images.githubusercontent.com/67386890/111352554-a46aab00-86c7-11eb-958f-b33963e6fe8d.png)

**Comment by MarcinAman** [comment] 2021-03-17 11:43
I think that there is a little bit of a confusion around what `suppressObviousFunctions` should do. The main idea was to hide `obvious` functions in dokka. That saying it is everything that is inherited from `java.lang.Object` or `java.lang.Enum` and in kotlin it is every function that is generated for case class (`componentN`, `equals`, `hashCode` etc) or inherited from `Any` or `Enum`. 
It was not designed to handle this issue but as it turns out lots of people are interested in having such functionality in dokka, so i'll do my best to add it to next version ☺️

**Closed** 2021-04-06 16:06 UTC
Labels: enhancement

**Comment by petruswrango** [comment] 2022-04-22 10:38
Above discussion did not resolve it for me. 
I should say that I'm using dokkaHtmlMultiModule, and not dokkaHtml.
What I ended up with was the the **module's** build.gradle.kts file:

```
tasks.dokkaHtmlPartial.configure {
    pluginConfiguration<org.jetbrains.dokka.base.DokkaBase, org.jetbrains.dokka.base.DokkaBaseConfiguration> {
        separateInheritedMembers = true
    }
}
```

Using dokka version 1.6.10

**Comment by Boodyahmedhamdy** [comment] 2024-09-18 14:03
using 1.9.20 with android and kotlin DSL. the code below was written in the `app` module `build.gradle` file. this code worked:

```kotlin

tasks.dokkaHtml.configure {
    outputDirectory.set(file("../docs/html")) 

    suppressInheritedMembers = true // this is the fix
}

```
