### ISSUE TITLE
javadocJar fails on jdk 10

### ISSUE THREAD

**Issue by ufoscout** [Kotlin/dokka#339] opened 2018-08-02 20:15 UTC
The plugin fails to execute with jdk 10.
Environment:
```
$ mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /home/ufo/Programs/maven
Java version: 10.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-29-generic", arch: "amd64", family: "unix"
```

Exception:
```
[ERROR] Failed to execute goal org.jetbrains.dokka:dokka-maven-plugin:0.9.17:javadocJar (default) on project oregold-be: Execution default of goal org.jetbrains.dokka:dokka-maven-plugin:0.9.17:javadocJar failed: A required class was missing while executing org.jetbrains.dokka:dokka-maven-plugin:0.9.17:javadocJar: com/sun/tools/doclets/formats/html/HtmlDoclet
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jetbrains.dokka:dokka-maven-plugin:0.9.17
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/ufo/workspaces/mvn-repository/org/jetbrains/dokka/dokka-maven-plugin/0.9.17/dokka-maven-plugin-0.9.17.jar
[ERROR] urls[1] = file:/home/ufo/workspaces/mvn-repository/org/jetbrains/dokka/dokka-fatjar/0.9.17/dokka-fatjar-0.9.17.jar
[ERROR] urls[2] = file:/home/ufo/workspaces/mvn-repository/org/apache/maven/maven-builder-support/3.5.0/maven-builder-support-3.5.0.jar
[ERROR] urls[3] = file:/home/ufo/workspaces/mvn-repository/com/google/guava/guava/20.0/guava-20.0.jar
[ERROR] urls[4] = file:/home/ufo/workspaces/mvn-repository/org/apache/maven/resolver/maven-resolver-util/1.0.3/maven-resolver-util-1.0.3.jar
[ERROR] urls[5] = file:/home/ufo/workspaces/mvn-repository/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar
[ERROR] urls[6] = file:/home/ufo/workspaces/mvn-repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[7] = file:/home/ufo/workspaces/mvn-repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
[ERROR] urls[8] = file:/home/ufo/workspaces/mvn-repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[9] = file:/home/ufo/workspaces/mvn-repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[10] = file:/home/ufo/workspaces/mvn-repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
[ERROR] urls[11] = file:/home/ufo/workspaces/mvn-repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[ERROR] urls[12] = file:/home/ufo/workspaces/mvn-repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[13] = file:/home/ufo/workspaces/mvn-repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[14] = file:/home/ufo/workspaces/mvn-repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[ERROR] urls[15] = file:/home/ufo/workspaces/mvn-repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[16] = file:/home/ufo/workspaces/mvn-repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[17] = file:/home/ufo/workspaces/mvn-repository/org/codehaus/plexus/plexus-archiver/3.4/plexus-archiver-3.4.jar
[ERROR] urls[18] = file:/home/ufo/workspaces/mvn-repository/org/codehaus/plexus/plexus-io/2.7.1/plexus-io-2.7.1.jar
[ERROR] urls[19] = file:/home/ufo/workspaces/mvn-repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[20] = file:/home/ufo/workspaces/mvn-repository/org/apache/commons/commons-compress/1.11/commons-compress-1.11.jar
[ERROR] urls[21] = file:/home/ufo/workspaces/mvn-repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[ERROR] urls[22] = file:/home/ufo/workspaces/mvn-repository/org/tukaani/xz/1.5/xz-1.5.jar
[ERROR] urls[23] = file:/home/ufo/workspaces/mvn-repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5/maven-plugin-annotations-3.5.jar
[ERROR] urls[24] = file:/home/ufo/workspaces/mvn-repository/com/github/olivergondza/maven-jdk-tools-wrapper/0.1/maven-jdk-tools-wrapper-0.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : com.sun.tools.doclets.formats.html.HtmlDoclet
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
```

**Comment by semoro** [comment] 2018-08-07 17:05
Duplicate of #294

**Closed** 2018-08-07 17:06 UTC
