### ISSUE TITLE
dokka-customFormat-example/dokkaCustomFormat not working

### ISSUE THREAD

**Issue by kjt0429** [Kotlin/dokka#2584] opened 2022-07-25 02:19 UTC
**Question**
dokka-customFormat-example not wokring

i just did below command line

./gradlew dokkaCustomForamtHtml

i expect that custom logo icon change . but not wokring

**Screenshots**
If applicable, add screenshots to help explain your problem

**Installation**
- Operating system: mac
- Build tool: Gradle v6.6.1
- Dokka version: 1.7.0

**Comment by IgnatBeresnev** [comment] 2022-07-25 12:42
Hi! Try simple `./gradlew dokkaHtml`. There's no indication that `dokkaCustomForamtHtml` exists.

We'll add more details on how to run example projects soon.

**Comment by vmishenev** [comment] 2022-07-28 12:15
Are you talking about [this example](https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-customFormat-example/build.gradle.kts)?
Then the needed task is called `dokkaCustomFormat`.
`./gradlew dokkaCustomFormat` should be executed.

**Comment by IgnatBeresnev** [comment] 2022-08-03 12:01
Closing as unable to reproduce / resolved for now, let us know if you still have this problem

Documentation will be updated with an example though.

**Closed by IgnatBeresnev** 2022-08-03 12:01 UTC
Labels: question, documentation
