### ISSUE TITLE
dokka does not inherit KDOC if subtype is not in same module

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#3230] opened 2023-10-17 20:41 UTC
**Describe the bug**
A clear and concise description of what the bug is 

Consider:

module A
```kotlin
interface A{
    /** some doc */
    val a : Int 
}
```

module B
```
class B: A {
   override val a = 1
}
```

**Expected behaviour**
if kdoc is defined in interface, then it is automatically used for subtypes (unless own KDOC is defined), regardless if interface and class are defined in same module or not (it works if it is defined in the same module).

At least in the context of a multi-module build it should work when dokkaHtmlMultiModule is used

**To Reproduce**
See code above

**Dokka configuration**

**Installation**
- Operating system: linux
- Build tool: Gradle v8.1.1
- Dokka version: 1.9.10

**Additional context**
Add any other context about the problem here

**Are you willing to provide a PR?**
Providing a PR can drastically speed up the process of fixing this bug

**Comment by vmishenev** [comment] 2023-10-21 23:43
This is a duplicate of #463

**Closed by vmishenev** 2023-10-21 23:43 UTC
Labels: bug

**Comment by robstoll** [comment] 2023-10-22 18:56
@vmishenev very similar indeed but in my case dokka already sees all necessary sources as it is in a multimodule project. for instance, linking from one module to the other works

**Comment by vmishenev** [comment] 2023-10-24 23:33
> dokka already sees all necessary sources as it is in a multimodule project.

Yes, but Dokka does not use the sources  from dependent modules, only built artifacts. I have described the situation in https://github.com/Kotlin/dokka/issues/3249
From this point of view, there is no difference between dependent submodules and external dependencies. See https://github.com/Kotlin/dokka/issues/463#issuecomment-1384464207

**Comment by robstoll** [comment] 2023-10-25 09:39
sorry, didn't see that the multimodul case is already discussed in the comments. all good then 👍
