### ISSUE TITLE
Error occurs when using 'javadoc' as output. 'html' as output works fine.

### ISSUE THREAD

**Issue by renescholze** [Kotlin/dokka#347] opened 2018-08-23 10:47 UTC
I got the following exception when I switch from the output format 'html' to 'javadoc'. The generation of the documentation with the 'html' format works fine.

I'm using the android gradle plugin 0.9.17
```
buildscript {
   ...
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
       ...

        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17"
    }
}

```

And the following task definition:
```
dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}
```

Exception:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':demo:dokka'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:178)
        at org.jetbrains.kotlin.asJava.elements.KtLightAnnotationForSourceEntry.getMemberValueAsCallArgument(lightAnnotations.kt:150)
        at org.jetbrains.kotlin.asJava.elements.KtLightAnnotationForSourceEntry.access$getMemberValueAsCallArgument(lightAnnotations.kt:69)
        at org.jetbrains.kotlin.asJava.elements.KtLightAnnotationForSourceEntry$wrapAnnotationValue$2.invoke(lightAnnotations.kt:257)
        at org.jetbrains.kotlin.asJava.elements.KtLightAnnotationForSourceEntry$wrapAnnotationValue$2.invoke(lightAnnotations.kt:69)
        at kotlin.SafePublicationLazyImpl.getValue(Lazy.kt:194)
        at org.jetbrains.kotlin.asJava.elements.KtLightAnnotationForSourceEntry$LightElementValue.getOriginalExpression(lightAnnotations.kt)
        at org.jetbrains.kotlin.asJava.elements.KtLightAnnotationForSourceEntry$LightElementValue.getText(lightAnnotations.kt:101)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.build(JavaPsiDocumentationBuilder.kt:283)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.nodeForElement(JavaPsiDocumentationBuilder.kt:103)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.build(JavaPsiDocumentationBuilder.kt:214)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder$build$4.invoke(JavaPsiDocumentationBuilder.kt:179)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder$build$4.invoke(JavaPsiDocumentationBuilder.kt:43)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendChildren(JavaPsiDocumentationBuilder.kt:130)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendMembers(JavaPsiDocumentationBuilder.kt:157)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.build(JavaPsiDocumentationBuilder.kt:179)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder$appendClasses$1.invoke(JavaPsiDocumentationBuilder.kt:69)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder$appendClasses$1.invoke(JavaPsiDocumentationBuilder.kt:43)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendChildren(JavaPsiDocumentationBuilder.kt:130)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendChildren$default(JavaPsiDocumentationBuilder.kt:126)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendClasses(JavaPsiDocumentationBuilder.kt:69)
        at org.jetbrains.dokka.KotlinAsJavaDocumentationBuilder.buildPackageDocumentation(KotlinAsJavaDocumentationBuilder.kt:36)
        at org.jetbrains.dokka.DocumentationBuilder.appendFragments(DocumentationBuilder.kt:418)
        at org.jetbrains.dokka.DokkaGeneratorKt.buildDocumentationModule(DokkaGenerator.kt:161)
        at org.jetbrains.dokka.DokkaGenerator.appendSourceModule(DokkaGenerator.kt:77)
        at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:40)
        at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:77)
        at org.jetbrains.dokka.DelegatedInvocationHandler.invoke(ProxyUtils.kt:41)
        at com.sun.proxy.$Proxy97.generate(Unknown Source)
        at org.jetbrains.dokka.gradle.DokkaTask.generate(main.kt:326)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

```

**Comment by semoro** [comment] 2018-08-23 14:01
Can you please, minimize sources that caused a problem and provide it?

**Comment by renescholze** [comment] 2018-08-24 05:03
I tried to minimize the source which should be selected by specify the sourceFiles parameter in the dokka task but it doesn't have an effect. The documentation is still build for all classes inside the project.

```
dokka {
    outputFormat = 'html|javadoc'
    outputDirectory = "$buildDir/javadoc"

    sourceDirs = files('path/to/source')
}
```

**Comment by Tvede-dk** [comment] 2018-09-30 17:44
I have the same issue, and its caused by a simple
```` kotlin
    @Throws //the issue
    @UiThread
    suspend fun inflate(@LayoutRes id: Int,
                        parent: ViewGroup? = null)
            : Deferred<View> = GlobalScope.async(inflaterQueue, block = {
        backgroundInflateView(id, parent)
                ?: inflateViewInUIThread(id, parent)
    })
````

but if I set the exceptions, it does not fail
eg:
```` kotlin
 @Throws(Throwable::class)
````

**Comment by Kordyjan** [comment] 2020-09-01 09:05
Javadoc generation was completely rewritten before 1.4.0-rc and this error was probably fixed in the process. If the bug still persists feel free to reopen the issue.

**Closed by Kordyjan** 2020-09-01 09:05 UTC
Labels: Javadoc
