### ISSUE TITLE
Enum members should not reveal constructor calls

### ISSUE THREAD

**Issue by cosinekitty** [Kotlin/dokka#2468] opened 2022-04-25 19:40 UTC
**Describe the bug**
I have a Kotlin project that includes several enum classes. There is a single source file [`astronomy.kt`](https://github.com/cosinekitty/astronomy/blob/8696241c9098df43c9d15d0e9785de2344852d54/source/kotlin/src/main/kotlin/io/github/cosinekitty/astronomy/astronomy.kt) that contains all the code and documentation comments. I am using Dokka to generate "GitHub Flavored Markdown" (gfm). When Dokka encounters an enum declaration like this...

```Kotlin
/**
 * The enumeration of celestial bodies supported by Astronomy Engine.
 */
enum class Body(
    internal val massProduct: Double?,
    internal val orbitalPeriod: Double?,
    internal val vsopModel: VsopModel?
) {
    /**
     * The planet Mercury.
     */
    Mercury(
        MERCURY_GM,
        87.969,
        VsopModel(vsopLonMercury, vsopLatMercury, vsopRadMercury)
    ),

    /**
     * The planet Venus.
     */
    Venus(
        VENUS_GM,
        224.701,
        VsopModel(vsopLonVenus, vsopLatVenus, vsopRadVenus)
    ),

    /*... etc ... */
}
```

... it inappropriately generates markdown that includes internal implementation details. Specifically, the members are listed with the internal details of the constructor calls. Enum constructors are required to be private, and in my case, the properties I am initializing are all marked internal. Here is an example of how the above Kotlin declaration for `Venus` gets converted to Markdown:

```
| [Venus](-venus/index.md) | [jvm]<br>[Venus](-venus/index.md)(VENUS_GM, 224.701, VsopModel(vsopLonVenus, vsopLatVenus, vsopRadVenus))<br>The planet Venus. |
```

**Expected behaviour**
The example for Venus above should look like this:

```
| [Venus](-venus/index.md) | [jvm]<br>The planet Venus. |
```

Outside users should not see internal implementation details of the enum member's construction. In general, I don't want source code leaking into my documentation; only the public parts of the interface should be exposed.

**Screenshots**
N/A

**To Reproduce**
1. Clone the [Astronomy Engine](https://github.com/cosinekitty/astronomy) repository and change into its directory.
2. `git checkout kotlin`
3. `cd source/kotlin`
4. `./gradlew dokkaGfm`
5. Look at the file `source/kotlin/build/dokka/gfm/astronomy/io.github.cosinekitty.astronomy/-body/index.md`. All of the internal constructor parameters are visible in the documentation. The same thing occurs in the markdown files for each individual enum member, such as `source/kotlin/build/dokka/gfm/astronomy/io.github.cosinekitty.astronomy/-body/-venus/index.md`.

**Dokka configuration**
Configuration of dokka used to reproduce the bug:

```Kotlin
plugins {
    java
    kotlin("jvm") version "1.6.10"
    `maven-publish`
    id("org.jetbrains.dokka") version "1.6.10"
}

group = "io.github.cosinekitty"
version = "0.0.1"

repositories {
    mavenCentral()
}

dependencies {
    dokkaHtmlPlugin("org.jetbrains.dokka:kotlin-as-java-plugin:1.6.10")
    val junit5Version = "5.8.2"
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-params:$junit5Version")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junit5Version")
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

val sourceJar by tasks.creating(Jar::class) {
    dependsOn(tasks["classes"])
    archiveClassifier.set("sources")
    from(sourceSets["main"].allSource)
}

task("fatJar", type = Jar::class) {
    from(configurations.runtimeClasspath.get().map(::zipTree))
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    with(tasks.jar.get())
}

publishing {
    publications {
        register("mavenJava", MavenPublication::class) {
            from(components["kotlin"])
            artifact(sourceJar)
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        allWarningsAsErrors = true
    }
}

tasks.dokkaGfm.configure {
    dokkaSourceSets {
        named("main") {
            includeNonPublic.set(false)
            reportUndocumented.set(true)
        }
    }
}

```

**Installation**
- Operating system: macOS/Windows/Linux: The bug happens in all 3: macOS, Windows 10, and multiple flavors of Debian Linux.
- Build tool: Gradle v7.4.1
- Dokka version: 1.6.10

**Additional context**
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.4.1
------------------------------------------------------------

Build time:   2022-03-09 15:04:47 UTC
Revision:     36dc52588e09b4b72f2010bc07599e0ee0434e2e

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (JetBrains s.r.o. 11.0.13+7-b1751.25)
OS:           Linux 4.19.0-20-amd64 amd64
```

**Are you willing to provide a PR?**
I am happy to provide whatever help the maintainers could use to reproduce/diagnose this bug. Thank you!

**Comment by IgnatBeresnev** [comment] 2022-04-25 20:35
Hi! Thank you for so many GFM-related bug reports, we appreciate it :) 

Just to let you know: right now we're focusing on making `html` and then `javadoc` formats stable, so it will take quite some time for us to get to `gfm`, but sooner or later it'll get some love :)

**Comment by cosinekitty** [comment] 2022-04-25 21:02
Thanks @IgnatBeresnev for letting me know. I have no idea how Dokka works internally, but I wonder if these issues are really specific to GFM, or are they general to the other output formas Dokka generates?

**Comment by IgnatBeresnev** [comment] 2022-04-25 21:35
> I wonder if these issues are really specific to GFM

Good thought, some bugs are indeed not specific to GFM and reside on the lower level. I'll check your reports for `html` format as well, thanks!

**Comment by ebraminio** [comment] 2022-05-06 15:11
@IgnatBeresnev Do you think you can also give me pointers so I can fix this? :) Apparently this was supposed to be fixed by https://github.com/Kotlin/dokka/commit/acd9234be6909a69f89600e9c8ddde642d36b1cf so I tested the code in this report to see if if is there anything special about it with no luck. In order to first write an end-to-end (from Kotlin code to resulting Gfm) I wished I could use `testInline` somewhere I could issue `CommonmarkRenderer` but found they are in separate module those confused where I can first put that test to start what is happening where.

**Comment by IgnatBeresnev** [comment] 2022-05-06 19:06
Hi! I'm not sure this is a bug that needs to be fixed

Described behavior doesn't just happen, there's logic written specifically for this, so I'm assuming it must've been for a reason. I understand it may not be relevant or desired by everyone, but still. Maybe it should be a toggable feature flag

I think this needs to be discussed first. If you want to implement it, we'll discuss internally what the desired behavior should be and I'll get back to you :)

**Comment by ebraminio** [comment] 2022-05-06 19:23
The problem is I suggested to use enum constructor calls instead raw enum for the project got the issue! 😄 Good part is that project haven't got block to Dokka's change so neither me nor OP don't have immediate use but I personally like to see Kotlin's documentation tools at the best shape! 😊

I indeed like to implement this, can you instruct me generally where to start maybe or anything regardless of intended behavior so I can work on it in parallel to your internal discussion? And I indeed won't push you much for merging the fix if I got the solution but you don't want have it in just that I'm more interested on the fix itself for now 😊. What I thought can be a start point is to find a place so I can put a Kotlin code and check its Gfm result which apparently not easily feasible but sure if I look harder guess it is possible to find where I should start.

**Comment by ebraminio** [comment] 2022-05-06 19:32
Or, let me first replicate this is in minimal separate project to see whether this is Gfm exclusive or can be seen with other outputs also or not, I'll be right back 😊

**Comment by cosinekitty** [comment] 2022-05-06 19:43
> Hi! I'm not sure this is a bug that needs to be fixed

I thought I would chime in on this one too. The reason I consider this behavior incorrect is that enum constructors are required to be private. Dokka is generating documentation that shows how a private class constructor is being called. For example:

```kotlin
Venus(
        VENUS_GM,
        224.701,
        VsopModel(vsopLonVenus, vsopLatVenus, vsopRadVenus)
    )
```

This is leaking internal implementation details -- actual executable code -- into my documentation. It is no different than if I wrote a function, declared it private or internal, and Dokka (or jsdoc, doxygen, etc.) included a line of code where that function is called as part of the documentation.

Since enum constructors are required by the Kotlin language spec to be private, there is never a reason to emit calls to those constructors as part of the documentation. It should be a general rule that nothing private or internal can appear in the generated documentation, because an outside caller has no access to it. It is additionally odd that any executable statements should appear; these are function calls, not interface declarations.

**Comment by cosinekitty** [comment] 2022-05-06 19:48
Just as a follow-up for clarification. In my example, `VsopModel` is an internal class. Users of my project don't know what it means, because it is never documented anywhere. I don't want this exposed in my documentation because it will just confuse people.

**Comment by ebraminio** [comment] 2022-05-06 19:54
Ok just checked it, this happens to both Gfm and Jekyll outputs but not Html and Javadoc so I think I can at least propose a fix so you may consider having it or not after your internal discussions :)

**Comment by ebraminio** [comment] 2022-05-06 20:40
Bare minimum to show this is gfm/jekull exclusive,

```
git clone https://github.com/ebraminio/dokka2468 && dokka2468
./gradlew dokkaGfm dokkaHtml dokkaJavadoc dokkaJekyll
grep -r 87.969 .
```

which results in:

```
./bin/main/io/github/ebraminio/dokka2468/Body.kt:enum class Body(internal val value: Double) { Mercury(87.969) }
./build/dokka/jekyll/dokka2468/io.github.ebraminio.dokka2468/-body/-mercury/index.md:[Mercury](index.html)(87.969)
./build/dokka/jekyll/dokka2468/io.github.ebraminio.dokka2468/-body/index.md:| [Mercury](-mercury/index.html) | [jvm]<br>[Mercury](-mercury/index.html)(87.969) |
./build/dokka/gfm/dokka2468/io.github.ebraminio.dokka2468/-body/-mercury/index.md:[Mercury](index.md)(87.969)
./build/dokka/gfm/dokka2468/io.github.ebraminio.dokka2468/-body/index.md:| [Mercury](-mercury/index.md) | [jvm]<br>[Mercury](-mercury/index.md)(87.969) |
./src/main/kotlin/io/github/ebraminio/dokka2468/Body.kt:enum class Body(internal val value: Double) { Mercury(87.969) }
```

but not html and javadoc one, I am now looking for a fix, so far I got lost but I shouldn't lose hope 😄

**Comment by ebraminio** [comment] 2022-05-07 10:38
Ok, so while I was playing around [this test](https://github.com/Kotlin/dokka/blob/2aabdea6113da6cb50edf18afb146b7120071e68/plugins/base/src/test/kotlin/enums/EnumsTest.kt#L280) I found regardless of visibility, `constructorSignature` method of that test unit prints all of the constructor signature. 

So turned to my minimal reproduction of the issue, https://github.com/ebraminio/dokka2468 and made the value field on https://github.com/ebraminio/dokka2468/blob/main/src/main/kotlin/io/github/ebraminio/dokka2468/Body.kt#L3 visible and found regardless of visibility dokkaGfm/dokkaJekyll print constructor signature but dokkaHtml/dokkaJavadoc don't print enum's constructor signature.

So I think maybe constructorSignature, just like html/javadoc (IIUC) probably shouldn't be printed at all anyway as even having public fields, I will see how they have become different and see if I can make them consistent. @IgnatBeresnev sorry for repeated spam, hopefully this message brings something on the table instead.

**Comment by IgnatBeresnev** [comment] 2022-05-12 15:54
Hi! We've disscussed this internally and agreed that exposing enum entry constructors is excessive, and we couldn't come up with any reason for why it was implemented or why it should persist in the future.

Having said that, we'd like to remove it from the content generation level (so even before rendering), which will affect all formats, not only GFM.

@ebraminio @cosinekitty is that something one of you might want to take on? :) You'd need to remove a few lines of code and a few classes, and then fix a bunch of tests, but mostly removing code. I'll add more details in case you show interest

**Comment by cosinekitty** [comment] 2022-05-12 17:05
Hi @IgnatBeresnev, yes, I would be interested in doing this work. So yes, more details about where to look would be very helpful.

**Comment by ebraminio** [comment] 2022-05-12 18:44
Same here as @cosinekitty! :)

**Comment by ebraminio** [comment] 2022-05-12 19:41
https://github.com/Kotlin/dokka/pull/2497 hopefully is in correct direction

**Comment by IgnatBeresnev** [comment] 2022-05-13 09:56
@ebraminio yep, seems like you got to it even before I did :)

**Closed** 2022-05-16 14:15 UTC
Labels: bug
