### ISSUE TITLE
Kotlin as Java failes to translate var-s

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1651] opened 2020-12-01 16:18 UTC
Minimal setup for reproduction with KAJ applied:

```kotlin
var jvmProperty2: Int = 23
```

failes with:
```
> Multiple pages associated with key: greeteer.example//jvmProperty2/#/PointingToDeclaration//DisplaySourceSet(sourceSetIDs=CompositeSourceSetID(children=[:dokkaHtml/jvmMain]), name=jvm, platform=jvm)
```

**Comment by swankjesse** [comment] 2022-04-27 03:43
A [similar crash](https://github.com/square/okhttp/runs/6187008005?check_suite_focus=true) is causing OkHttp’s releases to fail.

```
* What went wrong:
Execution failed for task ':okhttp:dokkaGfm'.
> Multiple pages associated with key: okhttp3/Request/tag/#/PointingToDeclaration//[DisplaySourceSet(sourceSetIDs=CompositeSourceSetID(children=[:okhttp:dokkaGfm/jvmMain]), name=jvm, platform=jvm)]
```

The Kotlin code that triggers this is admittedly pretty complicated. We have [two functions](https://github.com/square/okhttp/blob/master/okhttp/src/jvmMain/kotlin/okhttp3/Request.kt#L89-L99) that differ only by type parameters.

**Comment by IgnatBeresnev** [comment] 2022-04-27 13:12
@swankjesse have you been able to navigate around that? 

I think your case deserves a separate issue as it's not related to kotlin as java. Here's the link: https://github.com/Kotlin/dokka/issues/2473

**Comment by swankjesse** [comment] 2022-04-27 13:43
Ahh, makes sense. I got a similar stacktrace but there’s a different root cause. Thanks @IgnatBeresnev !

**Comment by IgnatBeresnev** [comment] 2023-03-14 00:41
Unable to reproduce this particular issue - looks like it's been fixed at some point. Dokka 1.8.10 outputs:

![2023-03-14_01-40-36](https://user-images.githubusercontent.com/22685910/224863043-45248944-1f7f-4f26-b729-41f4216e6f52.png)

___

I'll close the issue as implemented/fixed, but do let us know if you encounter anything related to this.

**Closed by IgnatBeresnev** 2023-03-14 00:41 UTC
Labels: bug, plugin: kotlin-as-java
