### ISSUE TITLE
Unable to load class 'org.jetbrains.dokka.model.AncestryNode'.

### ISSUE THREAD

**Issue by stantronic** [Kotlin/dokka#2445] opened 2022-04-16 15:40 UTC
**Describe the bug**
A clear and concise description of what the bug is 

dokkaHtml gradle task crashes with error "

**Expected behaviour**
A clear and concise description of what you expected to happen

dokkaHtml completes without error ```Unable to load class 'org.jetbrains.dokka.model.AncestryNode'.```

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
Steps to reproduce the behavior, ideally with an example project

**Dokka configuration**
Configuration of dokka used to reproduce the bug

Out of the box configuration on Android project

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.2
- Dokka version: 1.6.10

**Additional context**

Add any other context about the problem here

idea.log attached:
[idea.log](https://github.com/Kotlin/dokka/files/8500177/idea.log)

**Are you willing to provide a PR?**
Providing a PR can drastically speed up the process of fixing this bug

Sorry, no time at present

**Comment by IgnatBeresnev** [comment] 2022-04-16 16:13
Hi!

What version of android gradle plugin are you running, is it `7.1.X`? Is it a multi-module project? Is dokka applied for only one submodule? If the answers to all of these questions are "yes", please read https://github.com/Kotlin/dokka/issues/2436 and https://github.com/Kotlin/dokka/issues/2415, it contains workarounds (applying dokka in the root `build.gradle.kts`)

**Comment by IgnatBeresnev** [comment] 2022-04-26 19:01
I've collected all available information and workarounds in #2472, please have a look, hopefully it'll help.

I'll close this issue as a duplicate, but do let us know if proposed workarounds don't help and the problem is something else, we'll investigate.

**Closed by IgnatBeresnev** 2022-04-26 19:01 UTC
Labels: bug

**Comment by stantronic** [comment] 2022-04-26 19:36
Thanks. that put me on the right track.
