### ISSUE TITLE
Something's going wrong with intersection types

### ISSUE THREAD

**Issue by lowasser** [Kotlin/dokka#3066] opened 2023-07-07 23:08 UTC
On the Kotlin stdlib documentation, https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm.optionals/java.util.-optional/-any.html shows

```
fun <T> Optional<out T>.Any()
(source)
```

which lacks even a shown return type.

Clicking the source leads to the admittedly convoluted line of source

```
public fun <T> Optional<out T & Any>.getOrDefault(defaultValue: T): T = if (isPresent) get() else defaultValue
```

It took me a few minutes browsing to figure out what was going on, but the `getOrDefault` method doesn't actually appear by name anywhere in the generated docs.

**Expected behaviour**
I would expect the generated Dokka to show the signature

```
public fun <T> Optional<out T & Any>.getOrDefault(defaultValue: T): T
```

**Comment by vmishenev** [comment] 2023-08-09 18:15
Dokka support [Definitely non-nullable types](https://github.com/Kotlin/dokka/pull/2520) since 1.7.0.
This signature would be displayed in Dokka as:
![image](https://github.com/Kotlin/dokka/assets/9636937/1a5618d7-680c-456b-a2f6-d5b2a794c937)

But [https://kotlinlang.org/api/](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm.optionals/java.util.-optional/-any.html) is generated with very old Dokka. 
Migration StdLib to the latest Dokka is in progress. See  [KT-55392](https://youtrack.jetbrains.com/issue/KT-55392)  

Anyway, this issue is a duplicate of [KT-60968](https://youtrack.jetbrains.com/issue/KT-60968/kotlinlang.org-fails-to-display-APIs-with-Any-type-arguments)  in Kotlin Web Site.

**Closed by vmishenev** 2023-08-09 18:15 UTC
Labels: bug
