### ISSUE TITLE
Resolving methods/constructors parameter types (incl. generic ones)

### ISSUE THREAD

**Issue by Den-Rimus** [Kotlin/dokka#532] opened 2019-11-28 21:33 UTC
**Question**
Is it at all possible to have methods and constructors parameter types resolved as links? Either resolved externally (JVM/Kotlin types, Android SDK) or ones that can be linked in current project's javadoc. What about generic types?

**Screenshots**
![11-28 23-30-04(1)](https://user-images.githubusercontent.com/3531046/69832494-5c581880-1237-11ea-8522-f3952d9424f5.jpg)

These arrow-marked types could be resolved as links.

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.4.1
- Dokka version: 0.10.0

**Comment by kamilok1965** [comment] 2019-12-10 12:21
Not right now, I'm afraid. This is actually a duplicate of https://github.com/Kotlin/dokka/issues/165

**Comment by Kordyjan** [comment] 2020-09-02 08:30
It seems to be fixed after the rewrite of the javadoc renderer.

**Closed by Kordyjan** 2020-09-02 08:30 UTC
Labels: duplicate, question
