### ISSUE TITLE
Html: Modules with same short name but different path (full name) override each other

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/dokka#2437] opened 2022-04-13 14:10 UTC
**Describe the bug**
I have a project with nested modules. The module names are the same, but they are always in different sub modules.
```
| - a
| - - foo
| - b
|- - foo
```

**Expected behaviour**
two different modules, a.foo and b.foo

**Screenshots**
<img width="1920" alt="Bildschirmfoto 2022-04-13 um 16 06 22" src="https://user-images.githubusercontent.com/22521688/163198916-013b80b7-3d3b-49ea-9b9a-429706458214.png">

**To Reproduce**
[untitled3.zip](https://github.com/Kotlin/dokka/files/8482137/untitled3.zip)

`./gradlew dokkaHtmlMultiModule`

**Workaround**
```kotlin
// root build.gradle.kts
subprojects {
    tasks.getByName<DokkaTaskPartial>("dokkaHtmlPartial") {
        moduleName.set(project.path.drop(1).replace(":", " "))
    }
}
```

**Dokka configuration**
Nothing special: 
```Kotlin
// root build.gradle.kts
plugins {
    kotlin("jvm") version "1.6.20" apply false
    id("org.jetbrains.dokka") version "1.6.10"
}

// settings.gradle.kts
include(":a:foo")
include(":b:foo")

// a.foo/b.foo build.gradle.kts
plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.4.2
- Dokka version: 1.6.10

**Are you willing to provide a PR?**
With help, sure.

**Comment by IgnatBeresnev** [comment] 2022-04-13 16:08
Thanks for the report!

Unfortunately, this is a known issue, duplicates are #2037, #2272, #2413

Hopefully, it'll be addressed soon

**Comment by hfhbd** [comment] 2022-04-13 16:10
Oh, I used the wrong search terms. 
With multi modules a tree based navigation sidebar would be helpful too.

**Comment by Jeffset** [comment] 2022-04-25 13:05
Well, the problem is deeper than we think. The Gradle itself has the same issue - https://github.com/gradle/gradle/issues/847. Had it for years now. So, basically, it prevents anybody from naming their subprojects in a way so they share a short name.

**Comment by IgnatBeresnev** [comment] 2022-04-26 17:59
Closing this as duplicate of https://github.com/Kotlin/dokka/issues/2272 to reduce spreading information in different issues

**Closed by IgnatBeresnev** 2022-04-26 17:59 UTC
Labels: bug
