### ISSUE TITLE
Treat warning/reports as errors

### ISSUE THREAD

**Issue by cmoine** [Kotlin/dokka#769] opened 2020-03-25 10:50 UTC
**Is your feature request related to a problem? Please describe**
The dokka generation reports problem such as:
`Unresolved function ...`
It would be nice to not only log those errors but set the build as failed in CI environnement

**Describe the solution you'd like**
Add an attribute in the dokka.configuration, such as `buildFailure = true` (false by default for backward compatibility)

**Comment by kamildoleglo** [comment] 2020-06-05 09:36
Closing as a duplicate of https://github.com/Kotlin/dokka/issues/459, please follow that issue for updates

**Closed by kamildoleglo** 2020-06-05 09:36 UTC
Labels: duplicate, enhancement
