### ISSUE TITLE
Publish Dokka binaries (and some other JB libraries) in another Maven repository

### ISSUE THREAD

**Issue by CommanderTvis** [Kotlin/dokka#1733] opened 2021-02-05 11:06 UTC
Builds using Dokka will crash in May when JFrog will close Bintray and JCenter. The `dokka-core`, `markdown` and `kotlinx-*` artifacts are published there, and should be evacuated to other repositories as as soon as possible. 

Also Dokka references korlibs libraries which are published only to JCenter (related issue is https://github.com/korlibs/korge-next/issues/153).

**Comment by kamildoleglo** [comment] 2021-02-05 11:09
Second duplicate of https://github.com/Kotlin/dokka/issues/1725

**Closed by kamildoleglo** 2021-02-05 11:09 UTC
Labels: duplicate, enhancement
