### ISSUE TITLE
dokkaHtml fails with "Property module should be initialized before get"

### ISSUE THREAD

**Issue by eleventigerssc** [Kotlin/dokka#1660] opened 2020-12-03 22:53 UTC
**Describe the bug**
When running `./gradlew x:dokkaHtml` the task fails with:

```
Caused by: java.lang.IllegalStateException: Property module should be initialized before get.
        at kotlin.properties.NotNullVar.getValue(Delegates.kt:62)
        at org.jetbrains.kotlin.cli.jvm.compiler.CliTraceHolder.getModule(CliTrace.kt)
        at org.jetbrains.kotlin.cli.jvm.compiler.CliKotlinAsJavaSupport.findClassOrObjectDeclarations(CliKotlinAsJavaSupport.kt:119)
        at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClassesAndObjects(JavaElementFinder.kt:72)
        at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClasses(JavaElementFinder.kt:58)
        at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClass(JavaElementFinder.kt:47)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:107)
        at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:84)
        at com.intellij.psi.impl.PsiElementFactoryImpl.createTypeByFQClassName(PsiElementFactoryImpl.java:383)
        at com.intellij.psi.PsiType.getTypeByName(PsiType.java:161)
        at com.intellij.psi.PsiType.getJavaLangObject(PsiType.java:173)
        at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:792)
        at com.intellij.psi.impl.source.PsiClassImpl.getSuperTypes(PsiClassImpl.java:218)
        at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser$parseClasslike$2.invokeSuspend(DefaultPsiToDocumentableTranslator.kt:199)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Expected behaviour**
`dokkHtml` does not fail or provided more useful error message of what went wrong.

**Screenshots**
N/A

**To Reproduce**
N/A

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dokkaHtml {
    moduleName = 'x'
    dokkaSourceSets {
        configureEach {
            sourceRoots.from(project(':a').file('src/main'))
        }
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.5.1
- Dokka version: 1.4.20

**Comment by kamildoleglo** [comment] 2020-12-03 23:25
Please use `.set()` instead of `=`, so `moduleName.set("x")`

**Comment by eleventigerssc** [comment] 2020-12-03 23:34
Same issue, it does not appear to be related to `moduleName`, not sure what happens in `CliTraceHolder`.

**Comment by kamildoleglo** [comment] 2020-12-04 01:44
Could you please share your project or create a minimal reproducible example?

**Comment by eleventigerssc** [comment] 2020-12-08 00:48
@kamildoleglo I am failing to create a repro in a simple project, will update here if I do.

**Comment by IgnatBeresnev** [comment] 2022-04-26 20:56
Closing this for now as `unable to reproduce`. Please let us know if you keep experiencing this issue.

**Closed by IgnatBeresnev** 2022-04-26 20:56 UTC
Labels: bug, awaiting response
