### ISSUE TITLE
 documentedVisibilities feature is not working properly

### ISSUE THREAD

**Issue by raghav1305** [Kotlin/dokka#2581] opened 2022-07-21 19:09 UTC
**Describe the bug**
The documentedVisibilities feature is not working properly

**Expected behaviour**
The correct variables/functions is not being displayed when the corresponding setting is used

Case 1: From the given dokka configuration, it is expected that dokka has to display the "PROTECTED" variables/fuc in the "EBE" package but it doesn't display it.

Case 2:  From the given dokka configuration, it is expected that dokka has to display the "PROTECTED" variables/fuc in all packages in the source set but it doesn't display it.

Case 3: When we put the documentedVisibilties.set before the perPackageOption, perPackageOptions are not being considered.

**Dokka configuration**
Case 1:
tasks.dokkaHtml.configure {
    outputDirectory.set(file("fokka"))
    dokkaSourceSets {
        named("main") {
            reportUndocumented.set(false)
            perPackageOption {
                matchingRegex.set("andr")
                suppress.set(true)
            }
            perPackageOption {
                matchingRegex.set("ebe")
                documentedVisibilities.set(setOf(DokkaConfiguration.Visibility.PROTECTED))
            }
        }
    }
}

Case 2:
tasks.dokkaHtml.configure {
    outputDirectory.set(file("fokka"))
    dokkaSourceSets {
        named("main") {
            reportUndocumented.set(false)
            perPackageOption {
                matchingRegex.set("andr")
                suppress.set(true)
            }
          documentedVisibilities.set(setOf(DokkaConfiguration.Visibility.PROTECTED))
        }
    }
}

Case 3:
tasks.dokkaHtml.configure {
    outputDirectory.set(file("fokka"))
    dokkaSourceSets {
        named("main") {
            reportUndocumented.set(false)
            documentedVisibilities.set(setOf(DokkaConfiguration.Visibility.PROTECTED))
            perPackageOption {
                matchingRegex.set("andr")
                suppress.set(true)
            }
        }
    }
} 
In this case, "andr" package is not being suppressed while documentation, it is visible.

**Installation**
- Operating system: macOS
- Build tool: Gradle 7.0.4
- Dokka version: 1.7.10

**Additional context**
Add any other context about the problem here

**Comment by IgnatBeresnev** [comment] 2022-07-28 13:26
Hi! I'm unable to reproduce your problems as such, but there might be some misunderstandings:
1. `matchingRegex.set("andr")` has to be a regualr experssion - make sure your package actually satisfies it. Usually, you'd see something like `matchingRegex.set("com.example.domain.package.andr.*")` 
2. When you specify `documentedVisibilities.set(setOf(DokkaConfiguration.Visibility.PROTECTED))` - only `protected` members will be visible, `public` is not enabled by default if you override the setting. So include **both** public and protected to see protected functions inside a public class.

If you're still having problems with this, could you create a small sample project that reproduces the problem? We'll over it together to see what's wrong

Regarding your cases, I checked each one with a slightly altered configuration and it works as expected on my end:
```kotlin
//Case 1:
tasks.dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            perPackageOption {
                matchingRegex.set("me.beresnev.dokka.debug.onlyinternal.*")
                suppress.set(true)
            }
            perPackageOption {
                matchingRegex.set("me.beresnev.dokka.debug.onlyprotected.*")
                documentedVisibilities.set(
                    setOf(
                        DokkaConfiguration.Visibility.PUBLIC,
                        DokkaConfiguration.Visibility.PROTECTED
                    )
                )
            }
        }
    }
}

//Case 2:
tasks.dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            perPackageOption {
                matchingRegex.set("me.beresnev.dokka.debug.onlyinternal.*")
                suppress.set(true)
            }
            documentedVisibilities.set(
                setOf(
                    DokkaConfiguration.Visibility.PUBLIC,
                    DokkaConfiguration.Visibility.PROTECTED
                )
            )
        }
    }
}

//Case 3:
tasks.dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            documentedVisibilities.set(
                setOf(
                    DokkaConfiguration.Visibility.PUBLIC,
                    DokkaConfiguration.Visibility.PROTECTED
                )
            )
            perPackageOption {
                matchingRegex.set("me.beresnev.dokka.debug.onlyinternal.*")
                suppress.set(true)
            }
        }
    }
}
```

**Comment by IgnatBeresnev** [comment] 2022-08-03 12:00
Closing this as unable to reproduce - please, let us know if you keep having this problem

**Closed by IgnatBeresnev** 2022-08-03 12:00 UTC
Labels: bug
