### ISSUE TITLE
[1.4.20-multimodule-dev-3] Protected declarations are missing from the documentation

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/dokka#1522] opened 2020-10-01 09:06 UTC
**Describe the bug**

Few classes don't have their protected methods listed in Dokka.
Classes:
https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/json/commonMain/src/kotlinx/serialization/json/JsonTransformingSerializer.kt
https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/json/commonMain/src/kotlinx/serialization/json/JsonContentPolymorphicSerializer.kt

Docs:
https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-transforming-serializer/index.html
https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-content-polymorphic-serializer/index.html

**Expected behaviour**

Methods, such as `transformDeserialize`, `transformSerialize` and `selectDeserializer` are listed in the documentation.

**To Reproduce**
`kotlinx-serialization` project, branch `dokka-fixed-revisions`, `./gradlew dokkaHtmlMultiModule`

**Dokka configuration**

https://github.com/Kotlin/kotlinx.serialization/blob/dokka-fixed-revisions/gradle/dokka.gradle#L17

**Installation**
- Operating system: macOS
- Build tool: Gradle 6.3
- Dokka version: 1.4.20-multimodule-dev-3

**Comment by mukeshsolanki** [comment] 2021-04-20 07:48
Do we have a fix for this??

**Comment by MarcinAman** [comment] 2021-04-26 10:46
Sory for the longer waiting time but it is like that by design. Protected members are not a part of public api, therefore `includeNonPublic` (which is set to false by default) should filter out those entries. You can change that by setting it to `true`

**Closed by MarcinAman** 2021-04-26 10:46 UTC
Labels: bug, libs feedback
