### ISSUE TITLE
dokkaHtml throws Channel error

### ISSUE THREAD

**Issue by marandaneto** [Kotlin/dokka#1791] opened 2021-03-17 12:13 UTC
**Describe the bug**
kotlinx.coroutines.channels.ChannelKt.Channel$default(ILkotlinx/coroutines/channels/BufferOverflow;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlinx/coroutines/channels/Channel;

**Expected behaviour**
works normally

**To Reproduce**
run ./gradlew build for https://github.com/getsentry/sentry-java/pull/1320/commits/095ac6704e6b04678b9bc9b41c7c21727713f918
fails for :sentry-servlet:dokkaHtml

**Dokka configuration**
https://github.com/getsentry/sentry-java/pull/1320/commits/095ac6704e6b04678b9bc9b41c7c21727713f918

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.8.1
- Dokka version: 1.4.30

**Additional context**
using https://github.com/vanniktech/gradle-maven-publish-plugin

**Comment by marandaneto** [comment] 2021-03-17 12:20
If I don't use the `resolutionStrategy` I fall to #1272

**Comment by kamildoleglo** [comment] 2021-03-17 13:35
This issue is most likely caused by the `Dependency Management Plugin` (see https://github.com/sdeleuze/spring-framework/pull/2) 
`kotlinx-coroutines-core` is getting downgraded to 1.3.8 from 1.4.1, which are not binary compatible

**Comment by marandaneto** [comment] 2021-03-22 08:34
related to spring FW indeed, bumping from 2.3.4 to 2.4.4 solved the issue, thanks for the tip @kamildoleglo

**Comment by IgnatBeresnev** [comment] 2022-04-26 20:35
Closing as fixed for now, let us know if you keep experiencing this issue

**Closed by IgnatBeresnev** 2022-04-26 20:35 UTC
Labels: bug
