### ISSUE TITLE
Unresolved link for `Inheritors` tab

### ISSUE THREAD

**Issue by BarkingBad** [Kotlin/dokka#1496] opened 2020-09-21 08:56 UTC
The issue is a corner case, when we have unmerged elements because of clashing DRI, then these elements have unmerged inheritors.

Probably we don't pass correctly sourceSet in InheritorsTransformer

![obraz](https://user-images.githubusercontent.com/32793002/93748774-15d60f00-fbf9-11ea-9213-968e886ae99e.png)

**Comment by IgnatBeresnev** [comment] 2022-04-27 14:37
Unable to reproduce for 1.6.21. Closing this for now until we find another reproducer.

![2022-04-27_17-35-25](https://user-images.githubusercontent.com/22685910/165543709-d773a23d-3955-4b84-8ece-7b4b968366ba.png)

**Closed by IgnatBeresnev** 2022-04-27 14:37 UTC
Labels: bug
