### ISSUE TITLE
1.6.20 Regression: Annotations on Java type parameters

### ISSUE THREAD

**Issue by owengray-google** [Kotlin/dokka#2388] opened 2022-03-15 12:00 UTC
**Describe the bug**
`<T> void foo(@Nullable java.util.List<@NonNull T> previousList)` creates a `TypeParameter` for `T` which has no annotations.

**Expected behaviour**
The created `TypeParameter` contains the `@NonNull` annotation.

(I'm not sure whether nullability is correct there, but it is not an error to put a `TYPE_USE` annotation there.)

**Screenshots**
<img width="898" alt="Screen Shot 2022-03-15 at 7 58 46 AM" src="https://user-images.githubusercontent.com/56644404/158373393-b1521f40-114a-474e-ae18-0c7891c9d140.png">

This is a regression in `1.6.10-dev-146` -> `1.6.20-M1-dev-148`

**Comment by IgnatBeresnev** [comment] 2022-03-15 12:20
@owengray-google hi! Is there a test that fails or how did you find this? I'll try to narrow it down, but I need to find a way to reproduce this or check the fix.

I looked at the changes between builds 146 and 148 -- either it's the kotlin update itself or something very not obvious that was broken during refactoring, as other updates don't seem related to it.

**Comment by IgnatBeresnev** [comment] 2022-03-15 12:25
Looks like I found the test [here](https://android-review.googlesource.com/c/platform/tools/dokka-devsite-plugin/+/2025145/1/src/test/java/com/google/devsite/renderer/converters/DocTagConverterTest.kt#695):
```kotlin
@Test // REGRESSION: go/dokka-upstream-bug/2388
fun `Full documentation parameters table has types with nullability annotations`() {
```

If I revert your changes in this test, it should reproduce the problem, right?

**Comment by IgnatBeresnev** [comment] 2022-03-17 13:36
Unfortunately, it looks like this problem comes from #2326 (`Refactor Ancestry Graphs`). 

@BarkingBad, any ideas off the top of your head?

How I reproduced it:

1. Clone devsite plugin, revert assert changes from [this commit](https://android-review.googlesource.com/c/platform/tools/dokka-devsite-plugin/+/2025145/1/src/test/java/com/google/devsite/renderer/converters/DocTagConverterTest.kt#695)
2. Run the test (`Full documentation parameters table has types with nullability annotations`), make sure it fails
3. Open dokka, revert #2326, make a local build and publish it to maven local
4. Use locally built dokka to run the devsite plugin test again, it should pass

**Comment by owengray-google** [comment] 2022-03-21 15:00
That CL [does have some changes](https://github.com/Kotlin/dokka/pull/2326/files#diff-668d7a8ff4c6e4cbebe200868a974fefc008dd4d1a8158a6d9b6db6603b72ec7) to the part of the code that does this.

I can't see off the top of my head what could be responsible. At the moment, my only guess is that the cause is that the handling of `PsiTypeParameter` went from using `type.annotations()` to `resolved.annotations()`, but I would guess that resolving the type doesn't disturb the annotations.

**Comment by IgnatBeresnev** [comment] 2022-03-28 16:24
> At the moment, my only guess is that the cause is that the handling of PsiTypeParameter went from using type.annotations() to resolved.annotations(), but I would guess that resolving the type doesn't disturb the annotations

It seems you are right :) Using `type.annotations()` instead of `resolved.annotations()` fixes the problem

I've written identical tests for Kotlin and Java, and interestingly enough, this bug is only reproducible for Java. Moreover, there's another issue (or feature, depends on how you look at it), which is to be expected if you think about it.

Take this code:
```
public <@Nullable T> void foo(List<T> param) {}
```
* Before, if you looked at the parameter `List<T> param`, its `TypeParameter#extra` was empty. 
* After - it's not, and it contains propagated `@Nullable` annotation.

Working on a fix now

**Comment by BarkingBad** [comment] 2022-03-28 16:31
I hope my fix will work, after all I tracked it down by comparing the changes and found out that the previous implementation was having this type as a parameter. Let me know if I could help you somehow @IgnatBeresnev

**Comment by IgnatBeresnev** [comment] 2022-03-28 16:52
Oh, I see, thanks!

I think I'll fix it today or tomorrow just so that we can proceed with testing 1.6.20, and I'll also add some unit tests to cover these cases.

But you'll need to rebase and maybe fix some conflicts, hopefully that's OK with you. I'll let you know once it's done

**Comment by IgnatBeresnev** [comment] 2022-03-30 12:12
Fixed in master and cherry-picked into the upcoming `1.6.20`

**Closed by IgnatBeresnev** 2022-03-30 12:12 UTC
Labels: bug, regression
