### ISSUE TITLE
Unable to run dokka with single target multiplatform project and kotlin 1.9.0

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3038] opened 2023-06-08 11:02 UTC
Dokka tasks for a multiplatform project with a single target fail with

```
* Exception is:
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':single-target-mpp-module:dokkaHtml'
Caused by: java.lang.UnsupportedOperationException: Empty collection can't be reduced.
	at org.jetbrains.dokka.gradle.kotlin.KotlinClasspathUtilsKt.classpathOf(kotlinClasspathUtils.kt:83)
	at org.jetbrains.dokka.gradle.kotlin.KotlinSourceSetGistKt$gistOf$3.call(KotlinSourceSetGist.kt:22)
	at org.jetbrains.dokka.gradle.kotlin.KotlinSourceSetGistKt$gistOf$3.call(KotlinSourceSetGist.kt)
```

**Installation**
- Dokka version: 1.8.20
- Kotlin Gradle plugin version: 1.9.0-Beta

**Comment by IgnatBeresnev** [comment] 2023-06-09 12:18
Note: the problem is in Dokka's Gradle plugin, in the code about classpath and dependency resolution, and it appeared because KGP 1.9.0 started returning different compilations as compared to KGP 1.8.20.

**Comment by IgnatBeresnev** [comment] 2023-08-16 01:10
To reduce the spread of information and keep the discussion in a single place, I'll close this issue in favour of https://github.com/Kotlin/dokka/issues/3122 - let's continue there if anyone has anything to add.

**Closed by IgnatBeresnev** 2023-08-16 01:10 UTC
Labels: bug, regression, runner: Gradle plugin
