### ISSUE TITLE
Displaying custom Annotation labels in the generated documentation

### ISSUE THREAD

**Issue by AristotelispetrosBobas-TomTom** [Kotlin/dokka#2783] opened 2022-12-20 16:17 UTC
**Is your feature request related to a problem? Please describe**
There is currently no way of including/displaying custom Annotations.

**Describe the solution you'd like**
A configuration option to include custom Annotations and display the Annotation labels in the generated documentation.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered

**Additional context**
We do not want to suppress these Annotations, just add them to the documentation.

**Comment by IgnatBeresnev** [comment] 2023-01-03 02:28
It looks like you're missing the [@MustBeDocumented](https://kotlinlang.org/docs/annotations.html) annotation on top of your annotation declaration.

Please, apply it and see if it helps, or provide an example/reproducer of your case.

___

Usage example:

```
@MustBeDocumented
annotation class MyCustomAnnotation

@MyCustomAnnotation
fun foo() {}
```

Generated documentation:

![2023-01-03_03-24-45](https://user-images.githubusercontent.com/22685910/210292819-1d5da822-47b0-45c0-9e02-a248d0208ec6.png)

**Comment by AristotelispetrosBobas-TomTom** [comment] 2023-01-03 09:01
Thanks for your reply, we will test this and report back

**Comment by AlexisRiksman-TomTom** [comment] 2023-01-10 10:33
@IgnatBeresnev : This indeed solves the issue. Thanks for helping us out !

**Comment by IgnatBeresnev** [comment] 2023-01-10 12:43
Awesome, thanks for confirming it!

I'll close the issue as resolved then :)

**Closed by IgnatBeresnev** 2023-01-10 12:43 UTC
Labels: enhancement, awaiting response
