### ISSUE TITLE
Dokka documentation is not correctly displayed in Android Studio / IntelliJ

### ISSUE THREAD

**Issue by pmerlet-at-didomi** [Kotlin/dokka#2297] opened 2022-01-05 17:01 UTC
When using Dokka to document a class, the documentation is correctly displayed in Android Studio. But then, when exporting library to mavenLocal using dokkaJavadoc, the generated library javadoc is correctly displayed for methods, but not for the class. 
Also it seems the documentation for methods is correctly displayed when writing a Java file, but not with a Kotlin file.

Test data class:
```
/**
 * Data class for which we want documentation
 */
data class DokkaData(
    /** A String value */
    val aString: String,
    /** An Integer value */
    val anInt: Int,
    /** Yes, a Boolean value. My favorite. */
    val aBoolean: Boolean) {

    /**
     * Checks that all values are representation of `1`
     */
    fun isOne() = aString == "1" && anInt == 1 && aBoolean
}
```

Correct information pop-ups in Android Studio:
![Capture d’écran 2022-01-04 à 18 36 32](https://user-images.githubusercontent.com/67579232/148256457-1c6dd256-ef77-4c97-aa0d-2e9d0cc4b774.png)

![Capture d’écran 2022-01-04 à 18 36 40](https://user-images.githubusercontent.com/67579232/148256485-a795c186-3581-464f-8211-a9d143c1d499.png)

Library gradle file:
```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
    id("org.jetbrains.dokka") version "1.6.10"
}

android {
    compileSdk 31

    defaultConfig {
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

task dokkaJavadocJar(type: Jar, dependsOn: dokkaJavadoc) {
    archiveClassifier.set("javadoc")
    from dokkaJavadoc.outputDirectory
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = "com.pmerlet.testlib"
            artifactId = "lib"
            version = "2.1-dataDoc"

            artifact("$buildDir/outputs/aar/${project.getName()}-release.aar")
            artifact(dokkaJavadocJar)
        }
    }
}
```

Released documentation for methods works correctly from Java files in Android Studio:
<img width="916" alt="Capture d’écran 2022-01-04 à 18 45 14" src="https://user-images.githubusercontent.com/67579232/148256836-af1418a4-3a68-47d6-bcb9-c4bf7caf0305.png">

But released documentation is not displayed from Kotlin files, and not for class and data class fields from Java files:
<img width="609" alt="Capture d’écran 2022-01-04 à 18 44 36" src="https://user-images.githubusercontent.com/67579232/148257023-bca23ded-ce59-4110-a8a0-1628defdac2a.png">

- Android Studio 2020.3.1 Patch 4
- Operating system: macOS 12.1
- Build tool: Gradle v7.0.2
- Dokka version: 1.6.10

**Comment by pmerlet-at-didomi** [comment] 2022-01-05 17:04
So far this is the only similar issue I found, and there is no answer. But the problem seems to be the same on IntelliJ as well.
https://issueexplorer.com/issue/Kotlin/dokka/2033

**Comment by pmerlet-at-didomi** [comment] 2022-01-05 17:50
ok, the original issue is still open, i don't know why i didn't find it before.
https://github.com/Kotlin/dokka/issues/2033

It was opened in July and didn't move at all since then? It is a blocker IMO, there is no point in using Dokka in a library as long as this issue exists.

**Comment by pmerlet-at-didomi** [comment] 2022-01-06 11:10
I took a closer look at the behavior, here are my findings:

- Class-level documentation is never displayed in IDE, whether it is about Java files or Kotlin files. For Java classes documentation, the IDE indicates that it looked to an URL which, when opened, correctly displays the class documentation. I am not familiar with how IDE retrieves the info, I just notice that there is no package indication in the page, could it be the reason?

<img width="667" alt="Capture d’écran 2022-01-06 à 11 24 20" src="https://user-images.githubusercontent.com/67579232/148368618-67d648f1-96a5-4c52-918d-36d221237924.png">

<img width="475" alt="Capture d’écran 2022-01-06 à 11 24 43" src="https://user-images.githubusercontent.com/67579232/148369066-cccc4bd8-06d7-4322-b20e-15bc8ddd77c0.png">

- Documentation of methods for Java classes
  - The documentation of Java methods correctly shows up in the IDE, unless they have a non-primitive type as parameter. In this case, the IDE will look at the label with method and arguments with full package name, but the real URL has only the parameter name in the label.

<img width="706" alt="Capture d’écran 2022-01-06 à 11 59 22" src="https://user-images.githubusercontent.com/67579232/148373364-99afab74-358a-479a-b095-3be7ced1f131.png">

<img width="1153" alt="Capture d’écran 2022-01-06 à 12 00 00" src="https://user-images.githubusercontent.com/67579232/148373375-903208cc-6850-456a-9dfc-57c1d438c73c.png">

- Documentation of methods for Kotlin classes
  - Displayed from a Java file: The behavior is the same as Java classes, except that primitives does not work as well because they are Kotlin primitives (IDE is looking for kotlin.Int for example)
  - Displayed from a Kotlin file: The IDE does not display any help for Kotlin classes when writing Kotlin files. It does not even give a clue about what URL it tried looking for.

<img width="840" alt="Capture d’écran 2022-01-06 à 12 09 44" src="https://user-images.githubusercontent.com/67579232/148374020-9882f621-cf81-4e58-a276-fd010e596e6f.png">

**Comment by IgnatBeresnev** [comment] 2022-04-26 19:16
Thanks for the report and your investigation!

I'll close this as a duplicate of #2033 to reduce the spread of information in different issues, please follow it if you want updates.

**Closed by IgnatBeresnev** 2022-04-26 19:16 UTC
Labels: bug
