### ISSUE TITLE
style.css is generated outside of the module directory

### ISSUE THREAD

**Issue by encodeering** [Kotlin/dokka#163] opened 2017-05-25 17:41 UTC
Hello,

would it be possible to provide a configuration for the style.css location?

Configuration

```
    moduleName = "hello-world"
    outputDirectory = "build/javadoc"
    outputFormat = "html"
```

Generated directory structure by dokka 0.9.13

```
build/
   javadoc/
     hello-world/
       index.html
       ...
     style.css
```

Would like to push the `javadoc/hello-world` directory to github pages.

Thank you very much.

**Comment by gobarcanin** [comment] 2017-11-02 10:40
I am facing the same problem, because I want to use dokka documentation in pages. This would help a lot and I presume that this is not too much work 😄

**Comment by asiljan** [comment] 2017-11-02 10:50
+1

**Comment by Schuwi** [comment] 2017-12-20 13:15
I'm having the same problem. The directory structure is very odd for single-module projects.

**Comment by DanySK** [comment] 2018-10-10 16:55
Same issue here.

**Comment by almayce** [comment] 2019-02-28 12:48
Same issue..

**Comment by ethauvin** [comment] 2019-09-24 16:07
Or at the very least implement #394

**Comment by jimfilippou** [comment] 2020-04-24 23:02
>  - for line in $(find ./public -name '*.html'); do sed -i 's/..\/style.css/style.css/g' ${line##* .}; done

This doesn't work 😢

**Comment by gnarea** [comment] 2020-09-09 10:12
Workaround for anyone using GitHub Actions + GitHub Pages:

```
      - name: Move Dokka's stylesheet
        run: |
          set -x -o nounset -o errexit -o pipefail
          cd ./build/javadoc
          mv ./style.css ./THE-NAME-OF-YOUR-MODULE/
          find . -name '*.html' -print0 | xargs -0 sed -i 's;../style.css;style.css;g'
```

**Comment by kibotu** [comment] 2020-11-30 13:46
I've added it as snippet for fixing it manually in case you want to run it on jenkins or the likes https://gist.github.com/kibotu/78f6f65497eef81222ca3fb9b785e38d

**Comment by gnarea** [comment] 2021-01-07 15:26
I've just upgraded to v1 and I'm having to use a more complex workaround because it isn't just the `style.css` that's outside the module directory, but lots of assets now. Here's what I'm doing with GitHub Actions + GitHub pages:

```
      - name: Move Dokka's assets
        run: |
          set -x -o nounset -o errexit -o pipefail
          cd ./build/dokka/html
          mv ./styles ./images ./scripts navigation.html ./THE-NAME-OF-YOUR-MODULE/
          find ./poweb/ -name '*.html' -print0 | xargs -0 sed -i 's;../styles/;styles/;g'
          find ./poweb/ -name '*.html' -print0 | xargs -0 sed -i 's;../images/;images/;g'
          find ./poweb/ -name '*.html' -print0 | xargs -0 sed -i 's;../scripts/;scripts/;g'
          find ./poweb/ -name '*.html' -print0 | xargs -0 sed -i 's;pathToRoot = "../;pathToRoot = ";g'
          sed -i 's;href="poweb/;href=";g' ./poweb/navigation.html
```

**Comment by atyrin** [comment] 2022-09-09 08:30
Hi everyone! I see that the issue has a lot of upvotes, but is it still actual?
If we are talking about the `dokkaHtml` task in non a multimodule scenario, then the structure in the latest release version looks like
````
build/
   dokka/
     hello-world/
     styles/
       …
       style.css
     images/
     scripts/
     index.html
```
Seems like a valid structure.

But I see that @gnarea still experiences a problem and moves assets in the module folder. What is the reason behind it? Isn't it possible to push the whole `dokka` folder? Or is it some GitHub Pages limitation?

**Comment by FWDekker** [comment] 2022-09-11 22:00
@atyrin I don't think the issue is still actual. I upvoted the issue when it was originally opened, but in my projects the latest version of Dokka no longer places the styles outside of the module directory.

**Comment by atyrin** [comment] 2022-09-12 14:41
I'm closing the issue since the problem is not actual anymore in the form as described in the top message.
If you still experience similar troubles with the latest Dokka releases, please submit a new issue.

**Closed by atyrin** 2022-09-12 14:41 UTC
Labels: enhancement
