### ISSUE TITLE
extension function not reported if erased type has same signature

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#408] opened 2019-01-20 10:56 UTC
I have the following functions:
```
fun <T : CharSequence> Assert<T>.isEmpty()
fun <T : Collection<*>> Assert<T>.isEmpty()
fun <T : Map<*, *>> Assert<T>.isEmpty()
```
Only the function for CharSequence is reported, the one for Collection and Map aren't. If I change the one of Map to the following
```
fun Assert<out Map<*, *>>.isEmpty()
```
then it is reported as well. So I guess it is a problem related to type erasure or similar. Just a wild guess, the upper bound is ignored which makes all functions to look the same `Assert<Any>.isEmpty()`

**Comment by kamilok1965** [comment] 2019-10-03 15:35
This is probably a duplicate of https://github.com/Kotlin/dokka/issues/408

**Comment by robstoll** [comment] 2019-11-22 19:49
@kamilok1965 a duplicate of itself? :wink:

**Comment by kamilok1965** [comment] 2019-12-10 12:19
Oh, this was supposed to be in another issue, which I cannot find right now

**Comment by kamildoleglo** [comment] 2020-11-14 15:59
Fixed while rewriting dokka, fix confirmed in `1.4.10.2`

**Closed by kamildoleglo** 2020-11-14 15:59 UTC
Labels: bug, duplicate
