### ISSUE TITLE
Improve performance of creating documentation models

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/dokka#1493] opened 2020-09-19 04:38 UTC
We're investigating performance and found the bulk of the work is spent creating documentation models:

```
                           Initializing plugins:   111
                  Creating documentation models: 93410
Transforming documentation model before merging:   351
                   Merging documentation models:    25
 Transforming documentation model after merging:  1688
                                 Creating pages:     3
                             Transforming pages:    48
                                      Rendering:  5552
```

Unfortunately, this isn't because there's a lot of work to do, but rather because it isn't parallelized.  Monitoring the cores shows that only one is used at a time.

I believe the `DefaultPsiToDocumentableTranslator` and `DefaultDescriptorToDocumentableTranslator` can be parallelized. For example, parsing each class should be able to be done independently.

**Comment by kamildoleglo** [comment] 2020-09-21 09:33
Duplicate of https://github.com/Kotlin/dokka/issues/1212

**Closed** 2020-10-02 10:40 UTC
Labels: enhancement
