### ISSUE TITLE
Cannot resolve documentationFileName for dokkaMultiModule

### ISSUE THREAD

**Issue by fajarnuha** [Kotlin/dokka#1623] opened 2020-11-13 02:33 UTC
**Describe the bug**
Cannot resolve documentationFileName for dokkaMultiModule

**Expected behaviour**
Should work as described in the official documentation

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
just run as described 

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dokka { 
    outputFormat = 'html'
    ...
}
```

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v5.6.4
- Dokka version: 1.4.10.2

**Additional context**
Add any other context about the problem here

**Comment by MarcinAman** [comment] 2020-12-02 14:32
duplicate of #1530 
Also the `outputFormat` property is no longer valid with new dokka (format is determined by a gradle command)

**Closed by MarcinAman** 2020-12-02 14:32 UTC
Labels: bug
